
#line 1 "ejson.rl"
/*
 * IF YOU ARE LOOKING AT A .c FILE, YOUR ARE LOOKING AT THE WRONG ONE
 *
 * The .c file is autogenerated from a .rl source file for 'ragel'
 * parser generator.
 */
/*
	This file is part of libejson.
	
	(C) 2010 Michel Pollet <buserror@gmail.com>
	
	libejson is free software: you can redistribute it and/or modify
	it under the terms of the GNU Lesser General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.
	
	libejson is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU Lesser General Public License for more details.
	
	You should have received a copy of the GNU Lesser General Public License
	along with libejson.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include "ejson.h"


#line 36 "ejson.c"
static const char _ejson_str_eof_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 11, 
	13, 15, 17, 19, 21, 23, 25
};

static const int ejson_str_start = 6;
static const int ejson_str_first_final = 6;
static const int ejson_str_error = 0;

static const int ejson_str_en_main = 6;


#line 35 "ejson.rl"


static char * ejson_append_utf8_glyph(
	char * dst,
	unsigned long inUnicode )
{
	if (!(inUnicode & ~0x7f)) {
		*dst++ = ((char)inUnicode);
		return dst;	// that was easy
	}
	unsigned char *cur = (unsigned char*)dst;

	unsigned long currentMask = ~0x7ff;
	int bits = 6;
	int header = 5;

	while ((inUnicode & currentMask) && bits <= 24) {
		currentMask = currentMask << 6;
		bits += 6; header--;
	}
	*cur++ = (0xfe << header) | (unsigned char)(inUnicode >> (bits));
	bits -= 6;
	while (bits >= 0) {
		*cur++ = 0x80 | ((unsigned char)(inUnicode >> bits) & 0x3f);
		bits -= 6;
	}
	return (char*)cur;
}

int ejson_parse_string(const char * str, const char *end, char * out)
{
	const char *p = str, *pe = end ? end : str + strlen( str ), *eof = pe;
	int cs;
	out = out ? out : (char*)str;
	uint16_t u = 0;
	
#line 86 "ejson.c"
	{
	cs = ejson_str_start;
	}

#line 91 "ejson.c"
	{
	if ( p == pe )
		goto _test_eof;
	if ( cs == 0 )
		goto _out;
_resume:
	switch ( cs ) {
case 6:
	if ( (*p) == 92 )
		goto tr23;
	goto tr22;
case 1:
	switch( (*p) ) {
		case 34: goto tr1;
		case 92: goto tr2;
		case 98: goto tr3;
		case 102: goto tr4;
		case 110: goto tr5;
		case 114: goto tr6;
		case 116: goto tr7;
		case 117: goto tr8;
	}
	goto tr0;
case 7:
	if ( (*p) == 92 )
		goto tr25;
	goto tr24;
case 8:
	if ( (*p) == 92 )
		goto tr27;
	goto tr26;
case 9:
	if ( (*p) == 92 )
		goto tr29;
	goto tr28;
case 10:
	if ( (*p) == 92 )
		goto tr31;
	goto tr30;
case 11:
	if ( (*p) == 92 )
		goto tr33;
	goto tr32;
case 12:
	if ( (*p) == 92 )
		goto tr35;
	goto tr34;
case 13:
	if ( (*p) == 92 )
		goto tr37;
	goto tr36;
case 14:
	if ( (*p) == 92 )
		goto tr39;
	goto tr38;
case 2:
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr9;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr12;
	} else
		goto tr11;
	goto tr10;
case 0:
	goto _out;
case 3:
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr13;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr15;
	} else
		goto tr14;
	goto tr10;
case 4:
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr16;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr18;
	} else
		goto tr17;
	goto tr10;
case 5:
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr19;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr21;
	} else
		goto tr20;
	goto tr10;
	}

	tr10: cs = 0; goto _again;
	tr23: cs = 1; goto _again;
	tr25: cs = 1; goto f10;
	tr27: cs = 1; goto f12;
	tr29: cs = 1; goto f14;
	tr31: cs = 1; goto f16;
	tr33: cs = 1; goto f18;
	tr35: cs = 1; goto f20;
	tr37: cs = 1; goto f22;
	tr39: cs = 1; goto f24;
	tr8: cs = 2; goto _again;
	tr9: cs = 3; goto f0;
	tr11: cs = 3; goto f1;
	tr12: cs = 3; goto f2;
	tr13: cs = 4; goto f3;
	tr14: cs = 4; goto f4;
	tr15: cs = 4; goto f5;
	tr16: cs = 5; goto f3;
	tr17: cs = 5; goto f4;
	tr18: cs = 5; goto f5;
	tr19: cs = 6; goto f6;
	tr20: cs = 6; goto f7;
	tr21: cs = 6; goto f8;
	tr22: cs = 6; goto f9;
	tr24: cs = 6; goto f11;
	tr26: cs = 6; goto f13;
	tr28: cs = 6; goto f15;
	tr30: cs = 6; goto f17;
	tr32: cs = 6; goto f19;
	tr34: cs = 6; goto f21;
	tr36: cs = 6; goto f23;
	tr38: cs = 6; goto f25;
	tr0: cs = 7; goto _again;
	tr1: cs = 8; goto _again;
	tr2: cs = 9; goto _again;
	tr3: cs = 10; goto _again;
	tr4: cs = 11; goto _again;
	tr5: cs = 12; goto _again;
	tr6: cs = 13; goto _again;
	tr7: cs = 14; goto _again;

f3:
#line 74 "ejson.rl"
	{ u = (u << 4) | ((*p) - '0'); }
	goto _again;
f5:
#line 75 "ejson.rl"
	{ u = (u << 4) | ((*p) - 'a' + 0xa); }
	goto _again;
f4:
#line 76 "ejson.rl"
	{ u = (u << 4) | ((*p) - 'A' + 0xa); }
	goto _again;
f9:
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f12:
#line 82 "ejson.rl"
	{ *out++ = '"'; }
	goto _again;
f14:
#line 83 "ejson.rl"
	{ *out++ = '\\'; }
	goto _again;
f24:
#line 84 "ejson.rl"
	{ *out++ = '\t'; }
	goto _again;
f16:
#line 85 "ejson.rl"
	{ *out++ = '\b'; }
	goto _again;
f18:
#line 86 "ejson.rl"
	{ *out++ = '\f'; }
	goto _again;
f20:
#line 87 "ejson.rl"
	{ *out++ = '\n'; }
	goto _again;
f10:
#line 90 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f6:
#line 74 "ejson.rl"
	{ u = (u << 4) | ((*p) - '0'); }
#line 78 "ejson.rl"
	{ out = ejson_append_utf8_glyph(out, u); }
	goto _again;
f8:
#line 75 "ejson.rl"
	{ u = (u << 4) | ((*p) - 'a' + 0xa); }
#line 78 "ejson.rl"
	{ out = ejson_append_utf8_glyph(out, u); }
	goto _again;
f7:
#line 76 "ejson.rl"
	{ u = (u << 4) | ((*p) - 'A' + 0xa); }
#line 78 "ejson.rl"
	{ out = ejson_append_utf8_glyph(out, u); }
	goto _again;
f0:
#line 78 "ejson.rl"
	{ u = 0; }
#line 74 "ejson.rl"
	{ u = (u << 4) | ((*p) - '0'); }
	goto _again;
f2:
#line 78 "ejson.rl"
	{ u = 0; }
#line 75 "ejson.rl"
	{ u = (u << 4) | ((*p) - 'a' + 0xa); }
	goto _again;
f1:
#line 78 "ejson.rl"
	{ u = 0; }
#line 76 "ejson.rl"
	{ u = (u << 4) | ((*p) - 'A' + 0xa); }
	goto _again;
f13:
#line 82 "ejson.rl"
	{ *out++ = '"'; }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f15:
#line 83 "ejson.rl"
	{ *out++ = '\\'; }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f25:
#line 84 "ejson.rl"
	{ *out++ = '\t'; }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f17:
#line 85 "ejson.rl"
	{ *out++ = '\b'; }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f19:
#line 86 "ejson.rl"
	{ *out++ = '\f'; }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f21:
#line 87 "ejson.rl"
	{ *out++ = '\n'; }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f22:
#line 88 "ejson.rl"
	{ *out++ = '\r'; }
#line 90 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f11:
#line 90 "ejson.rl"
	{*out++ = (*p);}
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f23:
#line 88 "ejson.rl"
	{ *out++ = '\r'; }
#line 90 "ejson.rl"
	{*out++ = (*p);}
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;

_again:
	if ( cs == 0 )
		goto _out;
	if ( ++p != pe )
		goto _resume;
	_test_eof: {}
	if ( p == eof )
	{
	switch ( _ejson_str_eof_actions[cs] ) {
	case 13:
#line 82 "ejson.rl"
	{ *out++ = '"'; }
	break;
	case 15:
#line 83 "ejson.rl"
	{ *out++ = '\\'; }
	break;
	case 25:
#line 84 "ejson.rl"
	{ *out++ = '\t'; }
	break;
	case 17:
#line 85 "ejson.rl"
	{ *out++ = '\b'; }
	break;
	case 19:
#line 86 "ejson.rl"
	{ *out++ = '\f'; }
	break;
	case 21:
#line 87 "ejson.rl"
	{ *out++ = '\n'; }
	break;
	case 11:
#line 90 "ejson.rl"
	{*out++ = (*p);}
	break;
	case 23:
#line 88 "ejson.rl"
	{ *out++ = '\r'; }
#line 90 "ejson.rl"
	{*out++ = (*p);}
	break;
#line 412 "ejson.c"
	}
	}

	_out: {}
	}

#line 100 "ejson.rl"

	*out = 0;
	
	return 0;
}


#line 427 "ejson.c"
static const short _ejson_eof_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 23, 23, 0, 23, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 48, 0, 
	0, 0, 0, 48, 0, 0, 0, 23, 
	23, 0, 23, 0, 0, 48, 48, 48, 
	48, 0, 48, 48, 0, 0, 0, 0, 
	48, 0, 0, 0, 48, 0, 0, 0, 
	48, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 48, 0, 0, 0, 0, 
	48, 0, 0, 0, 23, 23, 0, 23, 
	0, 0, 48, 48, 48, 48, 0, 48, 
	48, 0, 0, 0, 0, 48, 0, 0, 
	0, 48, 0, 0, 0, 48, 0, 0, 
	0, 0, 0, 0, 0, 49, 0, 51, 
	53, 53, 55, 55, 57, 0, 59, 61, 
	63, 0, 0
};

static const int ejson_start = 1;
static const int ejson_first_final = 117;
static const int ejson_error = 0;

static const int ejson_en_ejson_value_list = 26;
static const int ejson_en_obj_field_list = 65;
static const int ejson_en_main = 1;


#line 109 "ejson.rl"


int ejson_parse( ejson_driver_t *d, const char * str )
{
	const char *p = str, *pe = str + strlen( str ), *eof = pe;
	int cs;
	int stack[48], top = 0;
	int integer_sign = 0;	// for integer decode
	const char * float_start = NULL;
	ejson_driver_value_t v; // = {0};
	uint32_t b64 = 0;
	int b64_cnt = 0;
	uint8_t * base64 = NULL;
	int base64_hold = 0;
	const char * _value_start = NULL;
	
	memset(&v, 0, sizeof(v));
	
#line 476 "ejson.c"
	{
	cs = ejson_start;
	top = 0;
	}

#line 482 "ejson.c"
	{
	if ( p == pe )
		goto _test_eof;
	if ( cs == 0 )
		goto _out;
_resume:
	switch ( cs ) {
case 1:
	switch( (*p) ) {
		case 32: goto tr0;
		case 34: goto tr2;
		case 37: goto tr3;
		case 43: goto tr4;
		case 45: goto tr5;
		case 46: goto tr6;
		case 48: goto tr7;
		case 91: goto tr9;
		case 102: goto tr10;
		case 110: goto tr11;
		case 116: goto tr12;
		case 123: goto tr13;
	}
	if ( (*p) > 10 ) {
		if ( 49 <= (*p) && (*p) <= 57 )
			goto tr8;
	} else if ( (*p) >= 9 )
		goto tr0;
	goto tr1;
case 0:
	goto _out;
case 2:
	switch( (*p) ) {
		case 34: goto tr15;
		case 92: goto tr16;
	}
	goto tr14;
case 3:
	switch( (*p) ) {
		case 34: goto tr18;
		case 92: goto tr19;
	}
	goto tr17;
case 117:
	if ( (*p) == 32 )
		goto tr335;
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr335;
	goto tr334;
case 118:
	if ( (*p) == 32 )
		goto tr337;
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr337;
	goto tr336;
case 4:
	if ( (*p) == 92 )
		goto tr19;
	goto tr17;
case 5:
	switch( (*p) ) {
		case 32: goto tr20;
		case 37: goto tr21;
		case 43: goto tr22;
		case 47: goto tr23;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr20;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr26;
		} else if ( (*p) >= 65 )
			goto tr25;
	} else
		goto tr24;
	goto tr1;
case 119:
	if ( (*p) == 32 )
		goto tr338;
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr338;
	goto tr334;
case 6:
	switch( (*p) ) {
		case 43: goto tr27;
		case 47: goto tr28;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr29;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr31;
	} else
		goto tr30;
	goto tr1;
case 7:
	switch( (*p) ) {
		case 43: goto tr32;
		case 47: goto tr33;
		case 61: goto tr35;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr34;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr37;
	} else
		goto tr36;
	goto tr1;
case 8:
	switch( (*p) ) {
		case 43: goto tr38;
		case 47: goto tr39;
		case 61: goto tr41;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr40;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr43;
	} else
		goto tr42;
	goto tr1;
case 9:
	switch( (*p) ) {
		case 32: goto tr45;
		case 37: goto tr46;
		case 43: goto tr47;
		case 47: goto tr48;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr45;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr51;
		} else if ( (*p) >= 65 )
			goto tr50;
	} else
		goto tr49;
	goto tr44;
case 10:
	switch( (*p) ) {
		case 32: goto tr52;
		case 37: goto tr53;
		case 43: goto tr54;
		case 47: goto tr55;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr52;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr58;
		} else if ( (*p) >= 65 )
			goto tr57;
	} else
		goto tr56;
	goto tr44;
case 11:
	if ( (*p) == 61 )
		goto tr59;
	goto tr1;
case 12:
	switch( (*p) ) {
		case 32: goto tr60;
		case 37: goto tr61;
		case 43: goto tr62;
		case 47: goto tr63;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr60;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr66;
		} else if ( (*p) >= 65 )
			goto tr65;
	} else
		goto tr64;
	goto tr44;
case 13:
	switch( (*p) ) {
		case 46: goto tr67;
		case 48: goto tr68;
	}
	if ( 49 <= (*p) && (*p) <= 57 )
		goto tr69;
	goto tr1;
case 14:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto tr70;
	goto tr1;
case 120:
	switch( (*p) ) {
		case 32: goto tr339;
		case 100: goto tr340;
		case 102: goto tr340;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr70;
	} else if ( (*p) >= 9 )
		goto tr339;
	goto tr334;
case 121:
	if ( (*p) == 32 )
		goto tr339;
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr339;
	goto tr334;
case 122:
	switch( (*p) ) {
		case 32: goto tr341;
		case 46: goto tr67;
		case 120: goto tr342;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr69;
	} else if ( (*p) >= 9 )
		goto tr341;
	goto tr334;
case 123:
	switch( (*p) ) {
		case 32: goto tr341;
		case 46: goto tr67;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr69;
	} else if ( (*p) >= 9 )
		goto tr341;
	goto tr334;
case 15:
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr71;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr73;
	} else
		goto tr72;
	goto tr1;
case 124:
	if ( (*p) == 32 )
		goto tr343;
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr343;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 70 ) {
			if ( 97 <= (*p) && (*p) <= 102 )
				goto tr73;
		} else if ( (*p) >= 65 )
			goto tr72;
	} else
		goto tr71;
	goto tr334;
case 125:
	if ( (*p) == 32 )
		goto tr337;
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr337;
	goto tr334;
case 16:
	if ( (*p) == 97 )
		goto tr74;
	goto tr1;
case 17:
	if ( (*p) == 108 )
		goto tr75;
	goto tr1;
case 18:
	if ( (*p) == 115 )
		goto tr76;
	goto tr1;
case 19:
	if ( (*p) == 101 )
		goto tr77;
	goto tr1;
case 126:
	if ( (*p) == 32 )
		goto tr344;
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr344;
	goto tr334;
case 20:
	if ( (*p) == 117 )
		goto tr78;
	goto tr1;
case 21:
	if ( (*p) == 108 )
		goto tr79;
	goto tr1;
case 22:
	if ( (*p) == 108 )
		goto tr80;
	goto tr1;
case 127:
	if ( (*p) == 32 )
		goto tr345;
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr345;
	goto tr334;
case 23:
	if ( (*p) == 114 )
		goto tr81;
	goto tr1;
case 24:
	if ( (*p) == 117 )
		goto tr82;
	goto tr1;
case 25:
	if ( (*p) == 101 )
		goto tr83;
	goto tr1;
case 128:
	if ( (*p) == 32 )
		goto tr346;
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr346;
	goto tr334;
case 26:
	if ( (*p) == 91 )
		goto tr84;
	goto tr1;
case 27:
	switch( (*p) ) {
		case 32: goto tr85;
		case 34: goto tr86;
		case 37: goto tr87;
		case 43: goto tr88;
		case 45: goto tr89;
		case 46: goto tr90;
		case 48: goto tr91;
		case 91: goto tr93;
		case 93: goto tr94;
		case 102: goto tr95;
		case 110: goto tr96;
		case 116: goto tr97;
		case 123: goto tr98;
	}
	if ( (*p) > 10 ) {
		if ( 49 <= (*p) && (*p) <= 57 )
			goto tr92;
	} else if ( (*p) >= 9 )
		goto tr85;
	goto tr1;
case 28:
	switch( (*p) ) {
		case 34: goto tr100;
		case 92: goto tr101;
	}
	goto tr99;
case 29:
	switch( (*p) ) {
		case 34: goto tr103;
		case 92: goto tr104;
	}
	goto tr102;
case 30:
	switch( (*p) ) {
		case 32: goto tr106;
		case 44: goto tr107;
		case 93: goto tr108;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr106;
	goto tr105;
case 31:
	switch( (*p) ) {
		case 32: goto tr109;
		case 44: goto tr85;
		case 93: goto tr94;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr109;
	goto tr1;
case 32:
	switch( (*p) ) {
		case 32: goto tr109;
		case 93: goto tr94;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr109;
	goto tr1;
case 129:
	goto tr347;
case 33:
	if ( (*p) == 92 )
		goto tr104;
	goto tr102;
case 34:
	switch( (*p) ) {
		case 32: goto tr110;
		case 37: goto tr111;
		case 43: goto tr112;
		case 47: goto tr113;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr110;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr116;
		} else if ( (*p) >= 65 )
			goto tr115;
	} else
		goto tr114;
	goto tr1;
case 35:
	switch( (*p) ) {
		case 32: goto tr117;
		case 44: goto tr118;
		case 93: goto tr119;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr117;
	goto tr105;
case 36:
	switch( (*p) ) {
		case 43: goto tr120;
		case 47: goto tr121;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr122;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr124;
	} else
		goto tr123;
	goto tr1;
case 37:
	switch( (*p) ) {
		case 43: goto tr125;
		case 47: goto tr126;
		case 61: goto tr128;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr127;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr130;
	} else
		goto tr129;
	goto tr1;
case 38:
	switch( (*p) ) {
		case 43: goto tr131;
		case 47: goto tr132;
		case 61: goto tr134;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr133;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr136;
	} else
		goto tr135;
	goto tr1;
case 39:
	switch( (*p) ) {
		case 32: goto tr137;
		case 37: goto tr138;
		case 43: goto tr139;
		case 47: goto tr140;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr137;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr143;
		} else if ( (*p) >= 65 )
			goto tr142;
	} else
		goto tr141;
	goto tr44;
case 40:
	switch( (*p) ) {
		case 32: goto tr144;
		case 37: goto tr145;
		case 43: goto tr146;
		case 47: goto tr147;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr144;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr150;
		} else if ( (*p) >= 65 )
			goto tr149;
	} else
		goto tr148;
	goto tr44;
case 41:
	if ( (*p) == 61 )
		goto tr151;
	goto tr1;
case 42:
	switch( (*p) ) {
		case 32: goto tr152;
		case 37: goto tr153;
		case 43: goto tr154;
		case 47: goto tr155;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr152;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr158;
		} else if ( (*p) >= 65 )
			goto tr157;
	} else
		goto tr156;
	goto tr44;
case 43:
	switch( (*p) ) {
		case 46: goto tr159;
		case 48: goto tr160;
	}
	if ( 49 <= (*p) && (*p) <= 57 )
		goto tr161;
	goto tr1;
case 44:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto tr162;
	goto tr1;
case 45:
	switch( (*p) ) {
		case 32: goto tr163;
		case 44: goto tr164;
		case 93: goto tr165;
		case 100: goto tr166;
		case 102: goto tr166;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr162;
	} else if ( (*p) >= 9 )
		goto tr163;
	goto tr105;
case 46:
	switch( (*p) ) {
		case 32: goto tr163;
		case 44: goto tr164;
		case 93: goto tr165;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr163;
	goto tr105;
case 47:
	switch( (*p) ) {
		case 32: goto tr167;
		case 44: goto tr168;
		case 46: goto tr159;
		case 93: goto tr169;
		case 120: goto tr170;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr161;
	} else if ( (*p) >= 9 )
		goto tr167;
	goto tr105;
case 48:
	switch( (*p) ) {
		case 32: goto tr167;
		case 44: goto tr168;
		case 46: goto tr159;
		case 93: goto tr169;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr161;
	} else if ( (*p) >= 9 )
		goto tr167;
	goto tr105;
case 49:
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr171;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr173;
	} else
		goto tr172;
	goto tr1;
case 50:
	switch( (*p) ) {
		case 32: goto tr174;
		case 44: goto tr175;
		case 93: goto tr176;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr174;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 70 ) {
			if ( 97 <= (*p) && (*p) <= 102 )
				goto tr173;
		} else if ( (*p) >= 65 )
			goto tr172;
	} else
		goto tr171;
	goto tr105;
case 51:
	switch( (*p) ) {
		case 32: goto tr177;
		case 44: goto tr85;
		case 93: goto tr94;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr177;
	goto tr105;
case 52:
	if ( (*p) == 97 )
		goto tr178;
	goto tr1;
case 53:
	if ( (*p) == 108 )
		goto tr179;
	goto tr1;
case 54:
	if ( (*p) == 115 )
		goto tr180;
	goto tr1;
case 55:
	if ( (*p) == 101 )
		goto tr181;
	goto tr1;
case 56:
	switch( (*p) ) {
		case 32: goto tr182;
		case 44: goto tr183;
		case 93: goto tr184;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr182;
	goto tr105;
case 57:
	if ( (*p) == 117 )
		goto tr185;
	goto tr1;
case 58:
	if ( (*p) == 108 )
		goto tr186;
	goto tr1;
case 59:
	if ( (*p) == 108 )
		goto tr187;
	goto tr1;
case 60:
	switch( (*p) ) {
		case 32: goto tr188;
		case 44: goto tr189;
		case 93: goto tr190;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr188;
	goto tr105;
case 61:
	if ( (*p) == 114 )
		goto tr191;
	goto tr1;
case 62:
	if ( (*p) == 117 )
		goto tr192;
	goto tr1;
case 63:
	if ( (*p) == 101 )
		goto tr193;
	goto tr1;
case 64:
	switch( (*p) ) {
		case 32: goto tr194;
		case 44: goto tr195;
		case 93: goto tr196;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr194;
	goto tr105;
case 65:
	if ( (*p) == 123 )
		goto tr197;
	goto tr1;
case 66:
	switch( (*p) ) {
		case 32: goto tr198;
		case 34: goto tr199;
		case 95: goto tr200;
		case 125: goto tr201;
	}
	if ( (*p) < 65 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr198;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr200;
	} else
		goto tr200;
	goto tr1;
case 67:
	switch( (*p) ) {
		case 34: goto tr203;
		case 92: goto tr204;
	}
	goto tr202;
case 68:
	switch( (*p) ) {
		case 34: goto tr206;
		case 92: goto tr207;
	}
	goto tr205;
case 69:
	switch( (*p) ) {
		case 32: goto tr208;
		case 40: goto tr209;
		case 58: goto tr210;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr208;
	goto tr1;
case 70:
	switch( (*p) ) {
		case 32: goto tr211;
		case 40: goto tr212;
		case 58: goto tr213;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr211;
	goto tr1;
case 71:
	switch( (*p) ) {
		case 32: goto tr211;
		case 58: goto tr213;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr211;
	goto tr1;
case 72:
	switch( (*p) ) {
		case 32: goto tr213;
		case 34: goto tr214;
		case 37: goto tr215;
		case 43: goto tr216;
		case 45: goto tr217;
		case 46: goto tr218;
		case 48: goto tr219;
		case 91: goto tr221;
		case 102: goto tr222;
		case 110: goto tr223;
		case 116: goto tr224;
		case 123: goto tr225;
	}
	if ( (*p) > 10 ) {
		if ( 49 <= (*p) && (*p) <= 57 )
			goto tr220;
	} else if ( (*p) >= 9 )
		goto tr213;
	goto tr1;
case 73:
	switch( (*p) ) {
		case 34: goto tr227;
		case 92: goto tr228;
	}
	goto tr226;
case 74:
	switch( (*p) ) {
		case 34: goto tr230;
		case 92: goto tr231;
	}
	goto tr229;
case 75:
	switch( (*p) ) {
		case 32: goto tr232;
		case 44: goto tr233;
		case 125: goto tr234;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr232;
	goto tr105;
case 76:
	switch( (*p) ) {
		case 32: goto tr235;
		case 44: goto tr198;
		case 125: goto tr201;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr235;
	goto tr1;
case 77:
	switch( (*p) ) {
		case 32: goto tr235;
		case 125: goto tr201;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr235;
	goto tr1;
case 130:
	goto tr348;
case 78:
	if ( (*p) == 92 )
		goto tr231;
	goto tr229;
case 79:
	switch( (*p) ) {
		case 32: goto tr236;
		case 37: goto tr237;
		case 43: goto tr238;
		case 47: goto tr239;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr236;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr242;
		} else if ( (*p) >= 65 )
			goto tr241;
	} else
		goto tr240;
	goto tr1;
case 80:
	switch( (*p) ) {
		case 32: goto tr243;
		case 44: goto tr244;
		case 125: goto tr245;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr243;
	goto tr105;
case 81:
	switch( (*p) ) {
		case 43: goto tr246;
		case 47: goto tr247;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr248;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr250;
	} else
		goto tr249;
	goto tr1;
case 82:
	switch( (*p) ) {
		case 43: goto tr251;
		case 47: goto tr252;
		case 61: goto tr254;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr253;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr256;
	} else
		goto tr255;
	goto tr1;
case 83:
	switch( (*p) ) {
		case 43: goto tr257;
		case 47: goto tr258;
		case 61: goto tr260;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr259;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr262;
	} else
		goto tr261;
	goto tr1;
case 84:
	switch( (*p) ) {
		case 32: goto tr263;
		case 37: goto tr264;
		case 43: goto tr265;
		case 47: goto tr266;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr263;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr269;
		} else if ( (*p) >= 65 )
			goto tr268;
	} else
		goto tr267;
	goto tr44;
case 85:
	switch( (*p) ) {
		case 32: goto tr270;
		case 37: goto tr271;
		case 43: goto tr272;
		case 47: goto tr273;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr270;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr276;
		} else if ( (*p) >= 65 )
			goto tr275;
	} else
		goto tr274;
	goto tr44;
case 86:
	if ( (*p) == 61 )
		goto tr277;
	goto tr1;
case 87:
	switch( (*p) ) {
		case 32: goto tr278;
		case 37: goto tr279;
		case 43: goto tr280;
		case 47: goto tr281;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr278;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr284;
		} else if ( (*p) >= 65 )
			goto tr283;
	} else
		goto tr282;
	goto tr44;
case 88:
	switch( (*p) ) {
		case 46: goto tr285;
		case 48: goto tr286;
	}
	if ( 49 <= (*p) && (*p) <= 57 )
		goto tr287;
	goto tr1;
case 89:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto tr288;
	goto tr1;
case 90:
	switch( (*p) ) {
		case 32: goto tr289;
		case 44: goto tr290;
		case 100: goto tr291;
		case 102: goto tr291;
		case 125: goto tr292;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr288;
	} else if ( (*p) >= 9 )
		goto tr289;
	goto tr105;
case 91:
	switch( (*p) ) {
		case 32: goto tr289;
		case 44: goto tr290;
		case 125: goto tr292;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr289;
	goto tr105;
case 92:
	switch( (*p) ) {
		case 32: goto tr293;
		case 44: goto tr294;
		case 46: goto tr285;
		case 120: goto tr295;
		case 125: goto tr296;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr287;
	} else if ( (*p) >= 9 )
		goto tr293;
	goto tr105;
case 93:
	switch( (*p) ) {
		case 32: goto tr293;
		case 44: goto tr294;
		case 46: goto tr285;
		case 125: goto tr296;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr287;
	} else if ( (*p) >= 9 )
		goto tr293;
	goto tr105;
case 94:
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr297;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr299;
	} else
		goto tr298;
	goto tr1;
case 95:
	switch( (*p) ) {
		case 32: goto tr300;
		case 44: goto tr301;
		case 125: goto tr302;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr300;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 70 ) {
			if ( 97 <= (*p) && (*p) <= 102 )
				goto tr299;
		} else if ( (*p) >= 65 )
			goto tr298;
	} else
		goto tr297;
	goto tr105;
case 96:
	switch( (*p) ) {
		case 32: goto tr303;
		case 44: goto tr198;
		case 125: goto tr201;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr303;
	goto tr105;
case 97:
	if ( (*p) == 97 )
		goto tr304;
	goto tr1;
case 98:
	if ( (*p) == 108 )
		goto tr305;
	goto tr1;
case 99:
	if ( (*p) == 115 )
		goto tr306;
	goto tr1;
case 100:
	if ( (*p) == 101 )
		goto tr307;
	goto tr1;
case 101:
	switch( (*p) ) {
		case 32: goto tr308;
		case 44: goto tr309;
		case 125: goto tr310;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr308;
	goto tr105;
case 102:
	if ( (*p) == 117 )
		goto tr311;
	goto tr1;
case 103:
	if ( (*p) == 108 )
		goto tr312;
	goto tr1;
case 104:
	if ( (*p) == 108 )
		goto tr313;
	goto tr1;
case 105:
	switch( (*p) ) {
		case 32: goto tr314;
		case 44: goto tr315;
		case 125: goto tr316;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr314;
	goto tr105;
case 106:
	if ( (*p) == 114 )
		goto tr317;
	goto tr1;
case 107:
	if ( (*p) == 117 )
		goto tr318;
	goto tr1;
case 108:
	if ( (*p) == 101 )
		goto tr319;
	goto tr1;
case 109:
	switch( (*p) ) {
		case 32: goto tr320;
		case 44: goto tr321;
		case 125: goto tr322;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr320;
	goto tr105;
case 110:
	switch( (*p) ) {
		case 32: goto tr212;
		case 95: goto tr323;
	}
	if ( (*p) < 65 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr212;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr323;
	} else
		goto tr323;
	goto tr1;
case 111:
	switch( (*p) ) {
		case 32: goto tr324;
		case 41: goto tr325;
		case 44: goto tr326;
		case 95: goto tr327;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr324;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr327;
		} else if ( (*p) >= 65 )
			goto tr327;
	} else
		goto tr327;
	goto tr1;
case 112:
	switch( (*p) ) {
		case 32: goto tr328;
		case 41: goto tr211;
		case 44: goto tr329;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr328;
	goto tr1;
case 113:
	switch( (*p) ) {
		case 32: goto tr328;
		case 41: goto tr211;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr328;
	goto tr1;
case 114:
	switch( (*p) ) {
		case 32: goto tr329;
		case 41: goto tr211;
		case 95: goto tr323;
	}
	if ( (*p) < 65 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr329;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr323;
	} else
		goto tr323;
	goto tr1;
case 115:
	if ( (*p) == 92 )
		goto tr207;
	goto tr205;
case 116:
	switch( (*p) ) {
		case 32: goto tr330;
		case 40: goto tr331;
		case 58: goto tr333;
		case 95: goto tr332;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr330;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr332;
		} else if ( (*p) >= 65 )
			goto tr332;
	} else
		goto tr332;
	goto tr1;
	}

	tr1: cs = 0; goto _again;
	tr44: cs = 0; goto f22;
	tr105: cs = 0; goto f47;
	tr334: cs = 0; goto f77;
	tr336: cs = 0; goto f78;
	tr347: cs = 0; goto f79;
	tr348: cs = 0; goto f80;
	tr0: cs = 1; goto _again;
	tr2: cs = 2; goto f0;
	tr17: cs = 3; goto _again;
	tr14: cs = 3; goto f8;
	tr19: cs = 4; goto _again;
	tr16: cs = 4; goto f8;
	tr20: cs = 5; goto _again;
	tr3: cs = 5; goto f1;
	tr45: cs = 5; goto f23;
	tr52: cs = 5; goto f29;
	tr60: cs = 5; goto f35;
	tr22: cs = 6; goto f11;
	tr23: cs = 6; goto f12;
	tr24: cs = 6; goto f13;
	tr25: cs = 6; goto f14;
	tr26: cs = 6; goto f15;
	tr47: cs = 6; goto f24;
	tr48: cs = 6; goto f25;
	tr49: cs = 6; goto f26;
	tr50: cs = 6; goto f27;
	tr51: cs = 6; goto f28;
	tr54: cs = 6; goto f30;
	tr55: cs = 6; goto f31;
	tr56: cs = 6; goto f32;
	tr57: cs = 6; goto f33;
	tr58: cs = 6; goto f34;
	tr62: cs = 6; goto f36;
	tr63: cs = 6; goto f37;
	tr64: cs = 6; goto f38;
	tr65: cs = 6; goto f39;
	tr66: cs = 6; goto f40;
	tr27: cs = 7; goto f16;
	tr28: cs = 7; goto f17;
	tr29: cs = 7; goto f18;
	tr30: cs = 7; goto f19;
	tr31: cs = 7; goto f20;
	tr32: cs = 8; goto f16;
	tr33: cs = 8; goto f17;
	tr34: cs = 8; goto f18;
	tr36: cs = 8; goto f19;
	tr37: cs = 8; goto f20;
	tr38: cs = 9; goto f16;
	tr39: cs = 9; goto f17;
	tr40: cs = 9; goto f18;
	tr42: cs = 9; goto f19;
	tr43: cs = 9; goto f20;
	tr41: cs = 10; goto f21;
	tr35: cs = 11; goto f21;
	tr59: cs = 12; goto f21;
	tr4: cs = 13; goto f2;
	tr5: cs = 13; goto f3;
	tr67: cs = 14; goto _again;
	tr6: cs = 14; goto f4;
	tr342: cs = 15; goto _again;
	tr10: cs = 16; goto f0;
	tr74: cs = 17; goto _again;
	tr75: cs = 18; goto _again;
	tr76: cs = 19; goto _again;
	tr11: cs = 20; goto f0;
	tr78: cs = 21; goto _again;
	tr79: cs = 22; goto _again;
	tr12: cs = 23; goto f0;
	tr81: cs = 24; goto _again;
	tr82: cs = 25; goto _again;
	tr85: cs = 27; goto _again;
	tr84: cs = 27; goto f45;
	tr107: cs = 27; goto f48;
	tr118: cs = 27; goto f50;
	tr164: cs = 27; goto f52;
	tr168: cs = 27; goto f54;
	tr175: cs = 27; goto f56;
	tr183: cs = 27; goto f58;
	tr189: cs = 27; goto f60;
	tr195: cs = 27; goto f62;
	tr86: cs = 28; goto f0;
	tr102: cs = 29; goto _again;
	tr99: cs = 29; goto f8;
	tr100: cs = 30; goto f9;
	tr103: cs = 30; goto f10;
	tr177: cs = 31; goto _again;
	tr106: cs = 31; goto f48;
	tr117: cs = 31; goto f50;
	tr163: cs = 31; goto f52;
	tr167: cs = 31; goto f54;
	tr174: cs = 31; goto f56;
	tr182: cs = 31; goto f58;
	tr188: cs = 31; goto f60;
	tr194: cs = 31; goto f62;
	tr109: cs = 32; goto _again;
	tr104: cs = 33; goto _again;
	tr101: cs = 33; goto f8;
	tr110: cs = 34; goto _again;
	tr87: cs = 34; goto f1;
	tr137: cs = 34; goto f23;
	tr144: cs = 34; goto f29;
	tr152: cs = 34; goto f35;
	tr111: cs = 35; goto _again;
	tr138: cs = 35; goto f23;
	tr145: cs = 35; goto f29;
	tr153: cs = 35; goto f35;
	tr112: cs = 36; goto f11;
	tr113: cs = 36; goto f12;
	tr114: cs = 36; goto f13;
	tr115: cs = 36; goto f14;
	tr116: cs = 36; goto f15;
	tr139: cs = 36; goto f24;
	tr140: cs = 36; goto f25;
	tr141: cs = 36; goto f26;
	tr142: cs = 36; goto f27;
	tr143: cs = 36; goto f28;
	tr146: cs = 36; goto f30;
	tr147: cs = 36; goto f31;
	tr148: cs = 36; goto f32;
	tr149: cs = 36; goto f33;
	tr150: cs = 36; goto f34;
	tr154: cs = 36; goto f36;
	tr155: cs = 36; goto f37;
	tr156: cs = 36; goto f38;
	tr157: cs = 36; goto f39;
	tr158: cs = 36; goto f40;
	tr120: cs = 37; goto f16;
	tr121: cs = 37; goto f17;
	tr122: cs = 37; goto f18;
	tr123: cs = 37; goto f19;
	tr124: cs = 37; goto f20;
	tr125: cs = 38; goto f16;
	tr126: cs = 38; goto f17;
	tr127: cs = 38; goto f18;
	tr129: cs = 38; goto f19;
	tr130: cs = 38; goto f20;
	tr131: cs = 39; goto f16;
	tr132: cs = 39; goto f17;
	tr133: cs = 39; goto f18;
	tr135: cs = 39; goto f19;
	tr136: cs = 39; goto f20;
	tr134: cs = 40; goto f21;
	tr128: cs = 41; goto f21;
	tr151: cs = 42; goto f21;
	tr88: cs = 43; goto f2;
	tr89: cs = 43; goto f3;
	tr159: cs = 44; goto _again;
	tr90: cs = 44; goto f4;
	tr162: cs = 45; goto _again;
	tr166: cs = 46; goto _again;
	tr91: cs = 47; goto f5;
	tr160: cs = 47; goto f41;
	tr92: cs = 48; goto f5;
	tr161: cs = 48; goto f41;
	tr170: cs = 49; goto _again;
	tr171: cs = 50; goto f42;
	tr172: cs = 50; goto f43;
	tr173: cs = 50; goto f44;
	tr93: cs = 51; goto f6;
	tr98: cs = 51; goto f7;
	tr95: cs = 52; goto f0;
	tr178: cs = 53; goto _again;
	tr179: cs = 54; goto _again;
	tr180: cs = 55; goto _again;
	tr181: cs = 56; goto _again;
	tr96: cs = 57; goto f0;
	tr185: cs = 58; goto _again;
	tr186: cs = 59; goto _again;
	tr187: cs = 60; goto _again;
	tr97: cs = 61; goto f0;
	tr191: cs = 62; goto _again;
	tr192: cs = 63; goto _again;
	tr193: cs = 64; goto _again;
	tr198: cs = 66; goto _again;
	tr233: cs = 66; goto f48;
	tr244: cs = 66; goto f50;
	tr290: cs = 66; goto f52;
	tr294: cs = 66; goto f54;
	tr301: cs = 66; goto f56;
	tr309: cs = 66; goto f58;
	tr315: cs = 66; goto f60;
	tr321: cs = 66; goto f62;
	tr197: cs = 66; goto f64;
	tr199: cs = 67; goto _again;
	tr205: cs = 68; goto _again;
	tr202: cs = 68; goto f8;
	tr203: cs = 69; goto f9;
	tr206: cs = 69; goto f10;
	tr208: cs = 70; goto f66;
	tr330: cs = 70; goto f76;
	tr211: cs = 71; goto _again;
	tr325: cs = 71; goto f75;
	tr213: cs = 72; goto _again;
	tr210: cs = 72; goto f66;
	tr333: cs = 72; goto f76;
	tr214: cs = 73; goto f0;
	tr229: cs = 74; goto _again;
	tr226: cs = 74; goto f8;
	tr227: cs = 75; goto f9;
	tr230: cs = 75; goto f10;
	tr303: cs = 76; goto _again;
	tr232: cs = 76; goto f48;
	tr243: cs = 76; goto f50;
	tr289: cs = 76; goto f52;
	tr293: cs = 76; goto f54;
	tr300: cs = 76; goto f56;
	tr308: cs = 76; goto f58;
	tr314: cs = 76; goto f60;
	tr320: cs = 76; goto f62;
	tr235: cs = 77; goto _again;
	tr231: cs = 78; goto _again;
	tr228: cs = 78; goto f8;
	tr236: cs = 79; goto _again;
	tr215: cs = 79; goto f1;
	tr263: cs = 79; goto f23;
	tr270: cs = 79; goto f29;
	tr278: cs = 79; goto f35;
	tr237: cs = 80; goto _again;
	tr264: cs = 80; goto f23;
	tr271: cs = 80; goto f29;
	tr279: cs = 80; goto f35;
	tr238: cs = 81; goto f11;
	tr239: cs = 81; goto f12;
	tr240: cs = 81; goto f13;
	tr241: cs = 81; goto f14;
	tr242: cs = 81; goto f15;
	tr265: cs = 81; goto f24;
	tr266: cs = 81; goto f25;
	tr267: cs = 81; goto f26;
	tr268: cs = 81; goto f27;
	tr269: cs = 81; goto f28;
	tr272: cs = 81; goto f30;
	tr273: cs = 81; goto f31;
	tr274: cs = 81; goto f32;
	tr275: cs = 81; goto f33;
	tr276: cs = 81; goto f34;
	tr280: cs = 81; goto f36;
	tr281: cs = 81; goto f37;
	tr282: cs = 81; goto f38;
	tr283: cs = 81; goto f39;
	tr284: cs = 81; goto f40;
	tr246: cs = 82; goto f16;
	tr247: cs = 82; goto f17;
	tr248: cs = 82; goto f18;
	tr249: cs = 82; goto f19;
	tr250: cs = 82; goto f20;
	tr251: cs = 83; goto f16;
	tr252: cs = 83; goto f17;
	tr253: cs = 83; goto f18;
	tr255: cs = 83; goto f19;
	tr256: cs = 83; goto f20;
	tr257: cs = 84; goto f16;
	tr258: cs = 84; goto f17;
	tr259: cs = 84; goto f18;
	tr261: cs = 84; goto f19;
	tr262: cs = 84; goto f20;
	tr260: cs = 85; goto f21;
	tr254: cs = 86; goto f21;
	tr277: cs = 87; goto f21;
	tr216: cs = 88; goto f2;
	tr217: cs = 88; goto f3;
	tr285: cs = 89; goto _again;
	tr218: cs = 89; goto f4;
	tr288: cs = 90; goto _again;
	tr291: cs = 91; goto _again;
	tr219: cs = 92; goto f5;
	tr286: cs = 92; goto f41;
	tr220: cs = 93; goto f5;
	tr287: cs = 93; goto f41;
	tr295: cs = 94; goto _again;
	tr297: cs = 95; goto f42;
	tr298: cs = 95; goto f43;
	tr299: cs = 95; goto f44;
	tr221: cs = 96; goto f6;
	tr225: cs = 96; goto f7;
	tr222: cs = 97; goto f0;
	tr304: cs = 98; goto _again;
	tr305: cs = 99; goto _again;
	tr306: cs = 100; goto _again;
	tr307: cs = 101; goto _again;
	tr223: cs = 102; goto f0;
	tr311: cs = 103; goto _again;
	tr312: cs = 104; goto _again;
	tr313: cs = 105; goto _again;
	tr224: cs = 106; goto f0;
	tr317: cs = 107; goto _again;
	tr318: cs = 108; goto _again;
	tr319: cs = 109; goto _again;
	tr212: cs = 110; goto _again;
	tr209: cs = 110; goto f66;
	tr331: cs = 110; goto f76;
	tr327: cs = 111; goto _again;
	tr323: cs = 111; goto f8;
	tr324: cs = 112; goto f75;
	tr328: cs = 113; goto _again;
	tr329: cs = 114; goto _again;
	tr326: cs = 114; goto f75;
	tr207: cs = 115; goto _again;
	tr204: cs = 115; goto f8;
	tr332: cs = 116; goto _again;
	tr200: cs = 116; goto f8;
	tr15: cs = 117; goto f9;
	tr18: cs = 117; goto f10;
	tr337: cs = 118; goto _again;
	tr335: cs = 118; goto f48;
	tr338: cs = 118; goto f50;
	tr339: cs = 118; goto f52;
	tr341: cs = 118; goto f54;
	tr343: cs = 118; goto f56;
	tr344: cs = 118; goto f58;
	tr345: cs = 118; goto f60;
	tr346: cs = 118; goto f62;
	tr21: cs = 119; goto _again;
	tr46: cs = 119; goto f23;
	tr53: cs = 119; goto f29;
	tr61: cs = 119; goto f35;
	tr70: cs = 120; goto _again;
	tr340: cs = 121; goto _again;
	tr7: cs = 122; goto f5;
	tr68: cs = 122; goto f41;
	tr8: cs = 123; goto f5;
	tr69: cs = 123; goto f41;
	tr71: cs = 124; goto f42;
	tr72: cs = 124; goto f43;
	tr73: cs = 124; goto f44;
	tr9: cs = 125; goto f6;
	tr13: cs = 125; goto f7;
	tr77: cs = 126; goto _again;
	tr80: cs = 127; goto _again;
	tr83: cs = 128; goto _again;
	tr94: cs = 129; goto f46;
	tr108: cs = 129; goto f49;
	tr119: cs = 129; goto f51;
	tr165: cs = 129; goto f53;
	tr169: cs = 129; goto f55;
	tr176: cs = 129; goto f57;
	tr184: cs = 129; goto f59;
	tr190: cs = 129; goto f61;
	tr196: cs = 129; goto f63;
	tr201: cs = 130; goto f65;
	tr234: cs = 130; goto f67;
	tr245: cs = 130; goto f68;
	tr292: cs = 130; goto f69;
	tr296: cs = 130; goto f70;
	tr302: cs = 130; goto f71;
	tr310: cs = 130; goto f72;
	tr316: cs = 130; goto f73;
	tr322: cs = 130; goto f74;

f64:
#line 128 "ejson.rl"
	{ d->open_object(d); }
	goto _again;
f45:
#line 130 "ejson.rl"
	{ d->open_array(d); }
	goto _again;
f66:
#line 132 "ejson.rl"
	{ d->set_name(d, &v); }
	goto _again;
f48:
#line 134 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_string, &v); }
	goto _again;
f62:
#line 138 "ejson.rl"
	{ v.u.v_bool = 1; d->set_value(d, ejson_driver_type_bool, &v); }
	goto _again;
f58:
#line 139 "ejson.rl"
	{ v.u.v_bool = 0; d->set_value(d, ejson_driver_type_bool, &v); }
	goto _again;
f60:
#line 140 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_null, NULL); }
	goto _again;
f50:
#line 159 "ejson.rl"
	{ 
			if (base64_hold && d->add_data)
				d->add_data(d, base64, base64_hold);
			if (d->close_data) d->close_data(d);
		}
	goto _again;
f8:
#line 172 "ejson.rl"
	{ v.u.v_str.start = v.u.v_str.end = p; }
	goto _again;
f10:
#line 173 "ejson.rl"
	{ v.u.v_str.end = p; }
	goto _again;
f41:
#line 183 "ejson.rl"
	{ v.u.v_int = (v.u.v_int * 10) + ((*p) - '0'); }
	goto _again;
f42:
#line 193 "ejson.rl"
	{ v.u.v_int = (v.u.v_int << 4) | ((*p) - '0'); }
	goto _again;
f44:
#line 194 "ejson.rl"
	{ v.u.v_int = (v.u.v_int << 4) | ((*p) - 'a' + 0xa); }
	goto _again;
f43:
#line 195 "ejson.rl"
	{ v.u.v_int = (v.u.v_int << 4) | ((*p) - 'A' + 0xa); }
	goto _again;
f19:
#line 216 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'A'); }
	goto _again;
f20:
#line 217 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'a' + 26 ); }
	goto _again;
f18:
#line 218 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - '0' + 52 ); }
	goto _again;
f16:
#line 219 "ejson.rl"
	{ b64 = (b64 << 6) | 62; }
	goto _again;
f17:
#line 220 "ejson.rl"
	{ b64 = (b64 << 6) | 63; }
	goto _again;
f21:
#line 222 "ejson.rl"
	{ b64 = (b64 << 6); }
	goto _again;
f22:
#line 237 "ejson.rl"
	{ printf("### base64 Error : '%s'\n", p); }
	goto _again;
f0:
#line 253 "ejson.rl"
	{ _value_start = p; }
	goto _again;
f47:
#line 254 "ejson.rl"
	{ printf("### Value[%d] Error : '%s'\n", top, _value_start); }
	goto _again;
f79:
#line 261 "ejson.rl"
	{ printf("### Array[%d] Error : '%s'\n", top, p); }
	goto _again;
f80:
#line 274 "ejson.rl"
	{ printf("### Object[%d] Error : '%s'\n", top, p); }
	goto _again;
f78:
#line 278 "ejson.rl"
	{ printf("### ejson Error : '%s'\n", p); }
	goto _again;
f65:
#line 129 "ejson.rl"
	{ d->close_object(d); }
#line 273 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f46:
#line 131 "ejson.rl"
	{ d->close_array(d); }
#line 260 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f9:
#line 172 "ejson.rl"
	{ v.u.v_str.start = v.u.v_str.end = p; }
#line 173 "ejson.rl"
	{ v.u.v_str.end = p; }
	goto _again;
f76:
#line 173 "ejson.rl"
	{ v.u.v_str.end = p; }
#line 132 "ejson.rl"
	{ d->set_name(d, &v); }
	goto _again;
f75:
#line 173 "ejson.rl"
	{ v.u.v_str.end = p; }
#line 133 "ejson.rl"
	{ if (d->add_flag) d->add_flag(d, &v); }
	goto _again;
f54:
#line 184 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 135 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_integer, &v); }
	goto _again;
f56:
#line 184 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 137 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_hex, &v); }
	goto _again;
f52:
#line 204 "ejson.rl"
	{ sscanf(float_start, "%lf", &v.u.v_float); }
#line 136 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_float, &v); }
	goto _again;
f23:
#line 225 "ejson.rl"
	{ b64_cnt = 3; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
	goto _again;
f29:
#line 230 "ejson.rl"
	{ b64_cnt = 2; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
	goto _again;
f35:
#line 232 "ejson.rl"
	{ b64_cnt = 1; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
	goto _again;
f14:
#line 236 "ejson.rl"
	{b64 = 0;}
#line 216 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'A'); }
	goto _again;
f15:
#line 236 "ejson.rl"
	{b64 = 0;}
#line 217 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'a' + 26 ); }
	goto _again;
f13:
#line 236 "ejson.rl"
	{b64 = 0;}
#line 218 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - '0' + 52 ); }
	goto _again;
f11:
#line 236 "ejson.rl"
	{b64 = 0;}
#line 219 "ejson.rl"
	{ b64 = (b64 << 6) | 62; }
	goto _again;
f12:
#line 236 "ejson.rl"
	{b64 = 0;}
#line 220 "ejson.rl"
	{ b64 = (b64 << 6) | 63; }
	goto _again;
f1:
#line 253 "ejson.rl"
	{ _value_start = p; }
#line 142 "ejson.rl"
	{ 
			if (d->open_data) {
				d->open_data(d);
				base64_hold = 0;
				if (!base64)
					base64 = (uint8_t*)alloca(128);
			}
		}
	goto _again;
f4:
#line 253 "ejson.rl"
	{ _value_start = p; }
#line 203 "ejson.rl"
	{ float_start = p; }
	goto _again;
f7:
#line 253 "ejson.rl"
	{ _value_start = p; }
#line 250 "ejson.rl"
	{ p--; {stack[top++] = cs; cs = 65; goto _again;} }
	goto _again;
f6:
#line 253 "ejson.rl"
	{ _value_start = p; }
#line 251 "ejson.rl"
	{ p--; {stack[top++] = cs; cs = 26; goto _again;} }
	goto _again;
f77:
#line 254 "ejson.rl"
	{ printf("### Value[%d] Error : '%s'\n", top, _value_start); }
#line 278 "ejson.rl"
	{ printf("### ejson Error : '%s'\n", p); }
	goto _again;
f67:
#line 134 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_string, &v); }
#line 129 "ejson.rl"
	{ d->close_object(d); }
#line 273 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f49:
#line 134 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_string, &v); }
#line 131 "ejson.rl"
	{ d->close_array(d); }
#line 260 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f74:
#line 138 "ejson.rl"
	{ v.u.v_bool = 1; d->set_value(d, ejson_driver_type_bool, &v); }
#line 129 "ejson.rl"
	{ d->close_object(d); }
#line 273 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f63:
#line 138 "ejson.rl"
	{ v.u.v_bool = 1; d->set_value(d, ejson_driver_type_bool, &v); }
#line 131 "ejson.rl"
	{ d->close_array(d); }
#line 260 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f72:
#line 139 "ejson.rl"
	{ v.u.v_bool = 0; d->set_value(d, ejson_driver_type_bool, &v); }
#line 129 "ejson.rl"
	{ d->close_object(d); }
#line 273 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f59:
#line 139 "ejson.rl"
	{ v.u.v_bool = 0; d->set_value(d, ejson_driver_type_bool, &v); }
#line 131 "ejson.rl"
	{ d->close_array(d); }
#line 260 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f73:
#line 140 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_null, NULL); }
#line 129 "ejson.rl"
	{ d->close_object(d); }
#line 273 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f61:
#line 140 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_null, NULL); }
#line 131 "ejson.rl"
	{ d->close_array(d); }
#line 260 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f68:
#line 159 "ejson.rl"
	{ 
			if (base64_hold && d->add_data)
				d->add_data(d, base64, base64_hold);
			if (d->close_data) d->close_data(d);
		}
#line 129 "ejson.rl"
	{ d->close_object(d); }
#line 273 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f51:
#line 159 "ejson.rl"
	{ 
			if (base64_hold && d->add_data)
				d->add_data(d, base64, base64_hold);
			if (d->close_data) d->close_data(d);
		}
#line 131 "ejson.rl"
	{ d->close_array(d); }
#line 260 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f2:
#line 253 "ejson.rl"
	{ _value_start = p; }
#line 181 "ejson.rl"
	{ v.u.v_int = 0; integer_sign = 1; }
#line 203 "ejson.rl"
	{ float_start = p; }
	goto _again;
f70:
#line 184 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 135 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_integer, &v); }
#line 129 "ejson.rl"
	{ d->close_object(d); }
#line 273 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f55:
#line 184 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 135 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_integer, &v); }
#line 131 "ejson.rl"
	{ d->close_array(d); }
#line 260 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f71:
#line 184 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 137 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_hex, &v); }
#line 129 "ejson.rl"
	{ d->close_object(d); }
#line 273 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f57:
#line 184 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 137 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_hex, &v); }
#line 131 "ejson.rl"
	{ d->close_array(d); }
#line 260 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f69:
#line 204 "ejson.rl"
	{ sscanf(float_start, "%lf", &v.u.v_float); }
#line 136 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_float, &v); }
#line 129 "ejson.rl"
	{ d->close_object(d); }
#line 273 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f53:
#line 204 "ejson.rl"
	{ sscanf(float_start, "%lf", &v.u.v_float); }
#line 136 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_float, &v); }
#line 131 "ejson.rl"
	{ d->close_array(d); }
#line 260 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f27:
#line 225 "ejson.rl"
	{ b64_cnt = 3; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 216 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'A'); }
	goto _again;
f28:
#line 225 "ejson.rl"
	{ b64_cnt = 3; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 217 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'a' + 26 ); }
	goto _again;
f26:
#line 225 "ejson.rl"
	{ b64_cnt = 3; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 218 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - '0' + 52 ); }
	goto _again;
f24:
#line 225 "ejson.rl"
	{ b64_cnt = 3; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 219 "ejson.rl"
	{ b64 = (b64 << 6) | 62; }
	goto _again;
f25:
#line 225 "ejson.rl"
	{ b64_cnt = 3; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 220 "ejson.rl"
	{ b64 = (b64 << 6) | 63; }
	goto _again;
f33:
#line 230 "ejson.rl"
	{ b64_cnt = 2; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 216 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'A'); }
	goto _again;
f34:
#line 230 "ejson.rl"
	{ b64_cnt = 2; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 217 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'a' + 26 ); }
	goto _again;
f32:
#line 230 "ejson.rl"
	{ b64_cnt = 2; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 218 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - '0' + 52 ); }
	goto _again;
f30:
#line 230 "ejson.rl"
	{ b64_cnt = 2; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 219 "ejson.rl"
	{ b64 = (b64 << 6) | 62; }
	goto _again;
f31:
#line 230 "ejson.rl"
	{ b64_cnt = 2; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 220 "ejson.rl"
	{ b64 = (b64 << 6) | 63; }
	goto _again;
f39:
#line 232 "ejson.rl"
	{ b64_cnt = 1; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 216 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'A'); }
	goto _again;
f40:
#line 232 "ejson.rl"
	{ b64_cnt = 1; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 217 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'a' + 26 ); }
	goto _again;
f38:
#line 232 "ejson.rl"
	{ b64_cnt = 1; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 218 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - '0' + 52 ); }
	goto _again;
f36:
#line 232 "ejson.rl"
	{ b64_cnt = 1; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 219 "ejson.rl"
	{ b64 = (b64 << 6) | 62; }
	goto _again;
f37:
#line 232 "ejson.rl"
	{ b64_cnt = 1; }
#line 150 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			for (int s=16, i = 0; i < b64_cnt; i++, s-=8) 
				base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 236 "ejson.rl"
	{b64 = 0;}
#line 220 "ejson.rl"
	{ b64 = (b64 << 6) | 63; }
	goto _again;
f3:
#line 253 "ejson.rl"
	{ _value_start = p; }
#line 181 "ejson.rl"
	{ v.u.v_int = 0; integer_sign = 1; }
#line 182 "ejson.rl"
	{ integer_sign = -1; }
#line 203 "ejson.rl"
	{ float_start = p; }
	goto _again;
f5:
#line 253 "ejson.rl"
	{ _value_start = p; }
#line 181 "ejson.rl"
	{ v.u.v_int = 0; integer_sign = 1; }
#line 183 "ejson.rl"
	{ v.u.v_int = (v.u.v_int * 10) + ((*p) - '0'); }
#line 203 "ejson.rl"
	{ float_start = p; }
	goto _again;

_again:
	if ( cs == 0 )
		goto _out;
	if ( ++p != pe )
		goto _resume;
	_test_eof: {}
	if ( p == eof )
	{
	switch ( _ejson_eof_actions[cs] ) {
	case 49:
#line 134 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_string, &v); }
	break;
	case 63:
#line 138 "ejson.rl"
	{ v.u.v_bool = 1; d->set_value(d, ejson_driver_type_bool, &v); }
	break;
	case 59:
#line 139 "ejson.rl"
	{ v.u.v_bool = 0; d->set_value(d, ejson_driver_type_bool, &v); }
	break;
	case 61:
#line 140 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_null, NULL); }
	break;
	case 51:
#line 159 "ejson.rl"
	{ 
			if (base64_hold && d->add_data)
				d->add_data(d, base64, base64_hold);
			if (d->close_data) d->close_data(d);
		}
	break;
	case 23:
#line 237 "ejson.rl"
	{ printf("### base64 Error : '%s'\n", p); }
	break;
	case 48:
#line 254 "ejson.rl"
	{ printf("### Value[%d] Error : '%s'\n", top, _value_start); }
	break;
	case 55:
#line 184 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 135 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_integer, &v); }
	break;
	case 57:
#line 184 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 137 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_hex, &v); }
	break;
	case 53:
#line 204 "ejson.rl"
	{ sscanf(float_start, "%lf", &v.u.v_float); }
#line 136 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_float, &v); }
	break;
#line 2815 "ejson.c"
	}
	}

	_out: {}
	}

#line 283 "ejson.rl"

	
	return 0;
};

