
#line 1 "ejson.rl"
/*
 * IF YOU ARE LOOKING AT A .c FILE, YOUR ARE LOOKING AT THE WRONG ONE
 *
 * The .c file is autogenerated from a .rl source file for 'ragel'
 * parser generator.
 */
/*
	This file is part of libejson.

	(C) 2010 Michel Pollet <buserror@gmail.com>

	libejson is free software: you can redistribute it and/or modify
	it under the terms of the GNU Lesser General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	libejson is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU Lesser General Public License for more details.

	You should have received a copy of the GNU Lesser General Public License
	along with libejson.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include "ejson.h"


#line 36 "ejson.c"
static const char _ejson_str_eof_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 11, 
	13, 15, 17, 19, 21, 23, 25, 0
};

static const int ejson_str_start = 6;
static const int ejson_str_first_final = 6;
static const int ejson_str_error = 0;

static const int ejson_str_en_main = 6;


#line 35 "ejson.rl"


static char * ejson_append_utf8_glyph(
	char * dst,
	unsigned long inUnicode )
{
	if (!(inUnicode & ~0x7f)) {
		*dst++ = ((char)inUnicode);
		return dst;	// that was easy
	}
	unsigned char *cur = (unsigned char*)dst;

	unsigned long currentMask = ~0x7ff;
	int bits = 6;
	int header = 5;

	while ((inUnicode & currentMask) && bits <= 24) {
		currentMask = currentMask << 6;
		bits += 6; header--;
	}
	*cur++ = (0xfe << header) | (unsigned char)(inUnicode >> (bits));
	bits -= 6;
	while (bits >= 0) {
		*cur++ = 0x80 | ((unsigned char)(inUnicode >> bits) & 0x3f);
		bits -= 6;
	}
	return (char*)cur;
}

int ejson_parse_string(const char * str, const char *end, char * out)
{
	const char *p = str, *pe = end ? end : str + strlen( str ), *eof = pe;
	int cs;
	out = out ? out : (char*)str;
	uint16_t u = 0;
	
#line 86 "ejson.c"
	{
	cs = ejson_str_start;
	}

#line 91 "ejson.c"
	{
	if ( p == pe )
		goto _test_eof;
	if ( cs == 0 )
		goto _out;
_resume:
	switch ( cs ) {
case 6:
	if ( (*p) == 92 )
		goto tr23;
	goto tr22;
case 1:
	switch( (*p) ) {
		case 34: goto tr1;
		case 92: goto tr2;
		case 98: goto tr3;
		case 102: goto tr4;
		case 110: goto tr5;
		case 114: goto tr6;
		case 116: goto tr7;
		case 117: goto tr8;
	}
	goto tr0;
case 7:
	if ( (*p) == 92 )
		goto tr25;
	goto tr24;
case 8:
	if ( (*p) == 92 )
		goto tr27;
	goto tr26;
case 9:
	if ( (*p) == 92 )
		goto tr29;
	goto tr28;
case 10:
	if ( (*p) == 92 )
		goto tr31;
	goto tr30;
case 11:
	if ( (*p) == 92 )
		goto tr33;
	goto tr32;
case 12:
	if ( (*p) == 92 )
		goto tr35;
	goto tr34;
case 13:
	if ( (*p) == 92 )
		goto tr37;
	goto tr36;
case 14:
	if ( (*p) == 92 )
		goto tr39;
	goto tr38;
case 2:
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr9;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr12;
	} else
		goto tr11;
	goto tr10;
case 0:
	goto _out;
case 3:
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr13;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr15;
	} else
		goto tr14;
	goto tr10;
case 4:
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr16;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr18;
	} else
		goto tr17;
	goto tr10;
case 5:
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr19;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr21;
	} else
		goto tr20;
	goto tr10;
case 15:
	if ( (*p) == 92 )
		goto tr23;
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr40;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr42;
	} else
		goto tr41;
	goto tr22;
	}

	tr10: cs = 0; goto _again;
	tr23: cs = 1; goto _again;
	tr25: cs = 1; goto f10;
	tr27: cs = 1; goto f12;
	tr29: cs = 1; goto f14;
	tr31: cs = 1; goto f16;
	tr33: cs = 1; goto f18;
	tr35: cs = 1; goto f20;
	tr37: cs = 1; goto f22;
	tr39: cs = 1; goto f24;
	tr8: cs = 2; goto _again;
	tr9: cs = 3; goto f0;
	tr11: cs = 3; goto f1;
	tr12: cs = 3; goto f2;
	tr13: cs = 4; goto f3;
	tr14: cs = 4; goto f4;
	tr15: cs = 4; goto f5;
	tr16: cs = 5; goto f3;
	tr17: cs = 5; goto f4;
	tr18: cs = 5; goto f5;
	tr22: cs = 6; goto f9;
	tr24: cs = 6; goto f11;
	tr26: cs = 6; goto f13;
	tr28: cs = 6; goto f15;
	tr30: cs = 6; goto f17;
	tr32: cs = 6; goto f19;
	tr34: cs = 6; goto f21;
	tr36: cs = 6; goto f23;
	tr38: cs = 6; goto f25;
	tr0: cs = 7; goto _again;
	tr1: cs = 8; goto _again;
	tr2: cs = 9; goto _again;
	tr3: cs = 10; goto _again;
	tr4: cs = 11; goto _again;
	tr5: cs = 12; goto _again;
	tr6: cs = 13; goto _again;
	tr7: cs = 14; goto _again;
	tr19: cs = 15; goto f6;
	tr20: cs = 15; goto f7;
	tr21: cs = 15; goto f8;
	tr40: cs = 15; goto f26;
	tr41: cs = 15; goto f27;
	tr42: cs = 15; goto f28;

f3:
#line 74 "ejson.rl"
	{ u = (u << 4) | ((*p) - '0'); }
	goto _again;
f5:
#line 75 "ejson.rl"
	{ u = (u << 4) | ((*p) - 'a' + 0xa); }
	goto _again;
f4:
#line 76 "ejson.rl"
	{ u = (u << 4) | ((*p) - 'A' + 0xa); }
	goto _again;
f9:
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f12:
#line 82 "ejson.rl"
	{ *out++ = '"'; }
	goto _again;
f14:
#line 83 "ejson.rl"
	{ *out++ = '\\'; }
	goto _again;
f24:
#line 84 "ejson.rl"
	{ *out++ = '\t'; }
	goto _again;
f16:
#line 85 "ejson.rl"
	{ *out++ = '\b'; }
	goto _again;
f18:
#line 86 "ejson.rl"
	{ *out++ = '\f'; }
	goto _again;
f20:
#line 87 "ejson.rl"
	{ *out++ = '\n'; }
	goto _again;
f10:
#line 90 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f6:
#line 74 "ejson.rl"
	{ u = (u << 4) | ((*p) - '0'); }
#line 78 "ejson.rl"
	{ out = ejson_append_utf8_glyph(out, u); }
	goto _again;
f8:
#line 75 "ejson.rl"
	{ u = (u << 4) | ((*p) - 'a' + 0xa); }
#line 78 "ejson.rl"
	{ out = ejson_append_utf8_glyph(out, u); }
	goto _again;
f7:
#line 76 "ejson.rl"
	{ u = (u << 4) | ((*p) - 'A' + 0xa); }
#line 78 "ejson.rl"
	{ out = ejson_append_utf8_glyph(out, u); }
	goto _again;
f0:
#line 78 "ejson.rl"
	{ u = 0; }
#line 74 "ejson.rl"
	{ u = (u << 4) | ((*p) - '0'); }
	goto _again;
f2:
#line 78 "ejson.rl"
	{ u = 0; }
#line 75 "ejson.rl"
	{ u = (u << 4) | ((*p) - 'a' + 0xa); }
	goto _again;
f1:
#line 78 "ejson.rl"
	{ u = 0; }
#line 76 "ejson.rl"
	{ u = (u << 4) | ((*p) - 'A' + 0xa); }
	goto _again;
f13:
#line 82 "ejson.rl"
	{ *out++ = '"'; }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f15:
#line 83 "ejson.rl"
	{ *out++ = '\\'; }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f25:
#line 84 "ejson.rl"
	{ *out++ = '\t'; }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f17:
#line 85 "ejson.rl"
	{ *out++ = '\b'; }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f19:
#line 86 "ejson.rl"
	{ *out++ = '\f'; }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f21:
#line 87 "ejson.rl"
	{ *out++ = '\n'; }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f22:
#line 88 "ejson.rl"
	{ *out++ = '\r'; }
#line 90 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f11:
#line 90 "ejson.rl"
	{*out++ = (*p);}
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f26:
#line 74 "ejson.rl"
	{ u = (u << 4) | ((*p) - '0'); }
#line 78 "ejson.rl"
	{ out = ejson_append_utf8_glyph(out, u); }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f28:
#line 75 "ejson.rl"
	{ u = (u << 4) | ((*p) - 'a' + 0xa); }
#line 78 "ejson.rl"
	{ out = ejson_append_utf8_glyph(out, u); }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f27:
#line 76 "ejson.rl"
	{ u = (u << 4) | ((*p) - 'A' + 0xa); }
#line 78 "ejson.rl"
	{ out = ejson_append_utf8_glyph(out, u); }
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;
f23:
#line 88 "ejson.rl"
	{ *out++ = '\r'; }
#line 90 "ejson.rl"
	{*out++ = (*p);}
#line 80 "ejson.rl"
	{*out++ = (*p);}
	goto _again;

_again:
	if ( cs == 0 )
		goto _out;
	if ( ++p != pe )
		goto _resume;
	_test_eof: {}
	if ( p == eof )
	{
	switch ( _ejson_str_eof_actions[cs] ) {
	case 13:
#line 82 "ejson.rl"
	{ *out++ = '"'; }
	break;
	case 15:
#line 83 "ejson.rl"
	{ *out++ = '\\'; }
	break;
	case 25:
#line 84 "ejson.rl"
	{ *out++ = '\t'; }
	break;
	case 17:
#line 85 "ejson.rl"
	{ *out++ = '\b'; }
	break;
	case 19:
#line 86 "ejson.rl"
	{ *out++ = '\f'; }
	break;
	case 21:
#line 87 "ejson.rl"
	{ *out++ = '\n'; }
	break;
	case 11:
#line 90 "ejson.rl"
	{*out++ = (*p);}
	break;
	case 23:
#line 88 "ejson.rl"
	{ *out++ = '\r'; }
#line 90 "ejson.rl"
	{*out++ = (*p);}
	break;
#line 451 "ejson.c"
	}
	}

	_out: {}
	}

#line 100 "ejson.rl"

	*out = 0;

	return 0;
}


#line 466 "ejson.c"
static const short _ejson_eof_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 24, 0, 0, 0, 24, 0, 
	24, 0, 24, 24, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 61, 0, 0, 0, 0, 61, 0, 
	0, 0, 24, 0, 0, 0, 24, 0, 
	24, 0, 24, 24, 0, 0, 61, 61, 
	0, 61, 0, 61, 0, 61, 0, 61, 
	0, 0, 0, 0, 61, 0, 0, 0, 
	61, 0, 0, 0, 61, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 61, 0, 0, 0, 
	0, 61, 0, 0, 0, 24, 0, 0, 
	0, 24, 0, 24, 0, 24, 24, 0, 
	0, 61, 61, 0, 61, 0, 61, 0, 
	61, 0, 61, 0, 0, 0, 0, 61, 
	0, 0, 0, 61, 0, 0, 0, 61, 
	0, 0, 0, 0, 0, 0, 0, 62, 
	0, 64, 66, 68, 66, 68, 70, 0, 
	72, 74, 76, 0, 0, 0
};

static const int ejson_start = 1;
static const int ejson_first_final = 151;
static const int ejson_error = 0;

static const int ejson_en_skipline = 36;
static const int ejson_en_ejson_value_list = 37;
static const int ejson_en_obj_field_list = 85;
static const int ejson_en_main = 1;


#line 109 "ejson.rl"


int ejson_parse( ejson_driver_t *d, const char * str )
{
	const char *p = str, *pe = str + strlen( str ), *eof = pe;
	int cs;
	int *stack = NULL, stack_size = 0, top = 0;
	int integer_sign = 0;	// for integer decode
	const char * float_start = NULL;
	char float_value[32];
	ejson_driver_value_t v; // = {0};
	uint32_t b64 = 0;
	int b64_cnt = 0;
	uint8_t * base64 = NULL;
	int base64_hold = 0;
	const char * _value_start = NULL;

	memset(&v, 0, sizeof(v));
	
#line 521 "ejson.c"
	{
	cs = ejson_start;
	top = 0;
	}

#line 527 "ejson.c"
	{
	if ( p == pe )
		goto _test_eof;
	if ( cs == 0 )
		goto _out;
_resume:
	switch ( cs ) {
case 1:
	switch( (*p) ) {
		case 32: goto tr0;
		case 34: goto tr2;
		case 37: goto tr3;
		case 43: goto tr4;
		case 45: goto tr5;
		case 46: goto tr6;
		case 47: goto tr7;
		case 48: goto tr8;
		case 91: goto tr10;
		case 102: goto tr11;
		case 110: goto tr12;
		case 116: goto tr13;
		case 123: goto tr14;
	}
	if ( (*p) > 10 ) {
		if ( 49 <= (*p) && (*p) <= 57 )
			goto tr9;
	} else if ( (*p) >= 9 )
		goto tr0;
	goto tr1;
case 0:
	goto _out;
case 2:
	switch( (*p) ) {
		case 34: goto tr16;
		case 92: goto tr17;
	}
	goto tr15;
case 3:
	switch( (*p) ) {
		case 34: goto tr19;
		case 92: goto tr20;
	}
	goto tr18;
case 151:
	switch( (*p) ) {
		case 32: goto tr449;
		case 47: goto tr450;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr449;
	goto tr448;
case 152:
	switch( (*p) ) {
		case 32: goto tr452;
		case 47: goto tr453;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr452;
	goto tr451;
case 4:
	if ( (*p) == 47 )
		goto tr21;
	goto tr1;
case 5:
	if ( (*p) == 92 )
		goto tr20;
	goto tr18;
case 6:
	switch( (*p) ) {
		case 32: goto tr22;
		case 37: goto tr23;
		case 43: goto tr24;
		case 47: goto tr25;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr22;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr28;
		} else if ( (*p) >= 65 )
			goto tr27;
	} else
		goto tr26;
	goto tr1;
case 153:
	switch( (*p) ) {
		case 32: goto tr454;
		case 47: goto tr455;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr454;
	goto tr448;
case 7:
	switch( (*p) ) {
		case 43: goto tr29;
		case 47: goto tr30;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr31;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr33;
	} else
		goto tr32;
	goto tr1;
case 8:
	switch( (*p) ) {
		case 43: goto tr34;
		case 47: goto tr35;
		case 61: goto tr37;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr36;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr39;
	} else
		goto tr38;
	goto tr1;
case 9:
	switch( (*p) ) {
		case 43: goto tr40;
		case 47: goto tr41;
		case 61: goto tr43;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr42;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr45;
	} else
		goto tr44;
	goto tr1;
case 10:
	switch( (*p) ) {
		case 32: goto tr47;
		case 37: goto tr48;
		case 43: goto tr49;
		case 47: goto tr50;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr47;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr53;
		} else if ( (*p) >= 65 )
			goto tr52;
	} else
		goto tr51;
	goto tr46;
case 11:
	switch( (*p) ) {
		case 43: goto tr29;
		case 47: goto tr54;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr31;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr33;
	} else
		goto tr32;
	goto tr1;
case 12:
	switch( (*p) ) {
		case 32: goto tr22;
		case 37: goto tr23;
		case 43: goto tr55;
		case 47: goto tr56;
		case 61: goto tr37;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr22;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr59;
		} else if ( (*p) >= 65 )
			goto tr58;
	} else
		goto tr57;
	goto tr1;
case 13:
	switch( (*p) ) {
		case 43: goto tr60;
		case 47: goto tr61;
		case 61: goto tr43;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr62;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr64;
	} else
		goto tr63;
	goto tr1;
case 14:
	switch( (*p) ) {
		case 32: goto tr47;
		case 37: goto tr48;
		case 43: goto tr65;
		case 47: goto tr66;
		case 61: goto tr37;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr47;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr69;
		} else if ( (*p) >= 65 )
			goto tr68;
	} else
		goto tr67;
	goto tr46;
case 15:
	switch( (*p) ) {
		case 43: goto tr60;
		case 47: goto tr70;
		case 61: goto tr43;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr62;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr64;
	} else
		goto tr63;
	goto tr1;
case 16:
	switch( (*p) ) {
		case 32: goto tr47;
		case 37: goto tr48;
		case 43: goto tr71;
		case 47: goto tr72;
		case 61: goto tr37;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr47;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr75;
		} else if ( (*p) >= 65 )
			goto tr74;
	} else
		goto tr73;
	goto tr46;
case 17:
	if ( (*p) == 61 )
		goto tr76;
	goto tr1;
case 18:
	switch( (*p) ) {
		case 32: goto tr77;
		case 37: goto tr78;
		case 43: goto tr79;
		case 47: goto tr80;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr77;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr83;
		} else if ( (*p) >= 65 )
			goto tr82;
	} else
		goto tr81;
	goto tr46;
case 19:
	switch( (*p) ) {
		case 32: goto tr84;
		case 37: goto tr85;
		case 43: goto tr86;
		case 47: goto tr87;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr84;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr90;
		} else if ( (*p) >= 65 )
			goto tr89;
	} else
		goto tr88;
	goto tr46;
case 20:
	switch( (*p) ) {
		case 46: goto tr91;
		case 48: goto tr92;
	}
	if ( 49 <= (*p) && (*p) <= 57 )
		goto tr93;
	goto tr1;
case 21:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto tr94;
	goto tr1;
case 154:
	switch( (*p) ) {
		case 32: goto tr456;
		case 47: goto tr457;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr94;
	} else if ( (*p) >= 9 )
		goto tr456;
	goto tr448;
case 155:
	switch( (*p) ) {
		case 32: goto tr458;
		case 46: goto tr459;
		case 47: goto tr460;
		case 101: goto tr461;
		case 120: goto tr462;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr93;
	} else if ( (*p) >= 9 )
		goto tr458;
	goto tr448;
case 22:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto tr95;
	goto tr1;
case 156:
	switch( (*p) ) {
		case 32: goto tr456;
		case 47: goto tr457;
		case 101: goto tr461;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr95;
	} else if ( (*p) >= 9 )
		goto tr456;
	goto tr448;
case 23:
	if ( (*p) == 45 )
		goto tr91;
	if ( 48 <= (*p) && (*p) <= 57 )
		goto tr94;
	goto tr1;
case 157:
	switch( (*p) ) {
		case 32: goto tr458;
		case 46: goto tr459;
		case 47: goto tr460;
		case 101: goto tr461;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr93;
	} else if ( (*p) >= 9 )
		goto tr458;
	goto tr448;
case 24:
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr96;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr98;
	} else
		goto tr97;
	goto tr1;
case 158:
	switch( (*p) ) {
		case 32: goto tr463;
		case 47: goto tr464;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr463;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 70 ) {
			if ( 97 <= (*p) && (*p) <= 102 )
				goto tr98;
		} else if ( (*p) >= 65 )
			goto tr97;
	} else
		goto tr96;
	goto tr448;
case 25:
	if ( (*p) == 47 )
		goto tr99;
	goto tr1;
case 159:
	switch( (*p) ) {
		case 32: goto tr452;
		case 47: goto tr453;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr452;
	goto tr448;
case 26:
	if ( (*p) == 97 )
		goto tr100;
	goto tr1;
case 27:
	if ( (*p) == 108 )
		goto tr101;
	goto tr1;
case 28:
	if ( (*p) == 115 )
		goto tr102;
	goto tr1;
case 29:
	if ( (*p) == 101 )
		goto tr103;
	goto tr1;
case 160:
	switch( (*p) ) {
		case 32: goto tr465;
		case 47: goto tr466;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr465;
	goto tr448;
case 30:
	if ( (*p) == 117 )
		goto tr104;
	goto tr1;
case 31:
	if ( (*p) == 108 )
		goto tr105;
	goto tr1;
case 32:
	if ( (*p) == 108 )
		goto tr106;
	goto tr1;
case 161:
	switch( (*p) ) {
		case 32: goto tr467;
		case 47: goto tr468;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr467;
	goto tr448;
case 33:
	if ( (*p) == 114 )
		goto tr107;
	goto tr1;
case 34:
	if ( (*p) == 117 )
		goto tr108;
	goto tr1;
case 35:
	if ( (*p) == 101 )
		goto tr109;
	goto tr1;
case 162:
	switch( (*p) ) {
		case 32: goto tr469;
		case 47: goto tr470;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr469;
	goto tr448;
case 36:
	if ( (*p) == 10 )
		goto tr111;
	goto tr110;
case 163:
	goto tr1;
case 37:
	if ( (*p) == 91 )
		goto tr112;
	goto tr1;
case 38:
	switch( (*p) ) {
		case 32: goto tr113;
		case 34: goto tr114;
		case 37: goto tr115;
		case 43: goto tr116;
		case 45: goto tr117;
		case 46: goto tr118;
		case 47: goto tr119;
		case 48: goto tr120;
		case 91: goto tr122;
		case 93: goto tr123;
		case 102: goto tr124;
		case 110: goto tr125;
		case 116: goto tr126;
		case 123: goto tr127;
	}
	if ( (*p) > 10 ) {
		if ( 49 <= (*p) && (*p) <= 57 )
			goto tr121;
	} else if ( (*p) >= 9 )
		goto tr113;
	goto tr1;
case 39:
	switch( (*p) ) {
		case 34: goto tr129;
		case 92: goto tr130;
	}
	goto tr128;
case 40:
	switch( (*p) ) {
		case 34: goto tr132;
		case 92: goto tr133;
	}
	goto tr131;
case 41:
	switch( (*p) ) {
		case 32: goto tr135;
		case 44: goto tr136;
		case 47: goto tr137;
		case 93: goto tr138;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr135;
	goto tr134;
case 42:
	switch( (*p) ) {
		case 32: goto tr139;
		case 44: goto tr113;
		case 47: goto tr140;
		case 93: goto tr123;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr139;
	goto tr1;
case 43:
	if ( (*p) == 47 )
		goto tr141;
	goto tr1;
case 164:
	goto tr471;
case 44:
	if ( (*p) == 92 )
		goto tr133;
	goto tr131;
case 45:
	switch( (*p) ) {
		case 32: goto tr142;
		case 37: goto tr143;
		case 43: goto tr144;
		case 47: goto tr145;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr142;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr148;
		} else if ( (*p) >= 65 )
			goto tr147;
	} else
		goto tr146;
	goto tr1;
case 46:
	switch( (*p) ) {
		case 32: goto tr149;
		case 44: goto tr150;
		case 47: goto tr151;
		case 93: goto tr152;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr149;
	goto tr134;
case 47:
	switch( (*p) ) {
		case 43: goto tr153;
		case 47: goto tr154;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr155;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr157;
	} else
		goto tr156;
	goto tr1;
case 48:
	switch( (*p) ) {
		case 43: goto tr158;
		case 47: goto tr159;
		case 61: goto tr161;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr160;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr163;
	} else
		goto tr162;
	goto tr1;
case 49:
	switch( (*p) ) {
		case 43: goto tr164;
		case 47: goto tr165;
		case 61: goto tr167;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr166;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr169;
	} else
		goto tr168;
	goto tr1;
case 50:
	switch( (*p) ) {
		case 32: goto tr170;
		case 37: goto tr171;
		case 43: goto tr172;
		case 47: goto tr173;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr170;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr176;
		} else if ( (*p) >= 65 )
			goto tr175;
	} else
		goto tr174;
	goto tr46;
case 51:
	switch( (*p) ) {
		case 43: goto tr153;
		case 47: goto tr177;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr155;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr157;
	} else
		goto tr156;
	goto tr1;
case 52:
	switch( (*p) ) {
		case 32: goto tr142;
		case 37: goto tr143;
		case 43: goto tr178;
		case 47: goto tr179;
		case 61: goto tr161;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr142;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr182;
		} else if ( (*p) >= 65 )
			goto tr181;
	} else
		goto tr180;
	goto tr1;
case 53:
	switch( (*p) ) {
		case 43: goto tr183;
		case 47: goto tr184;
		case 61: goto tr167;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr185;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr187;
	} else
		goto tr186;
	goto tr1;
case 54:
	switch( (*p) ) {
		case 32: goto tr170;
		case 37: goto tr171;
		case 43: goto tr188;
		case 47: goto tr189;
		case 61: goto tr161;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr170;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr192;
		} else if ( (*p) >= 65 )
			goto tr191;
	} else
		goto tr190;
	goto tr46;
case 55:
	switch( (*p) ) {
		case 43: goto tr183;
		case 47: goto tr193;
		case 61: goto tr167;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr185;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr187;
	} else
		goto tr186;
	goto tr1;
case 56:
	switch( (*p) ) {
		case 32: goto tr170;
		case 37: goto tr171;
		case 43: goto tr194;
		case 47: goto tr195;
		case 61: goto tr161;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr170;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr198;
		} else if ( (*p) >= 65 )
			goto tr197;
	} else
		goto tr196;
	goto tr46;
case 57:
	if ( (*p) == 61 )
		goto tr199;
	goto tr1;
case 58:
	switch( (*p) ) {
		case 32: goto tr200;
		case 37: goto tr201;
		case 43: goto tr202;
		case 47: goto tr203;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr200;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr206;
		} else if ( (*p) >= 65 )
			goto tr205;
	} else
		goto tr204;
	goto tr46;
case 59:
	switch( (*p) ) {
		case 32: goto tr207;
		case 37: goto tr208;
		case 43: goto tr209;
		case 47: goto tr210;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr207;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr213;
		} else if ( (*p) >= 65 )
			goto tr212;
	} else
		goto tr211;
	goto tr46;
case 60:
	switch( (*p) ) {
		case 46: goto tr214;
		case 48: goto tr215;
	}
	if ( 49 <= (*p) && (*p) <= 57 )
		goto tr216;
	goto tr1;
case 61:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto tr217;
	goto tr1;
case 62:
	switch( (*p) ) {
		case 32: goto tr218;
		case 44: goto tr219;
		case 47: goto tr220;
		case 93: goto tr221;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr217;
	} else if ( (*p) >= 9 )
		goto tr218;
	goto tr134;
case 63:
	switch( (*p) ) {
		case 32: goto tr222;
		case 44: goto tr223;
		case 46: goto tr224;
		case 47: goto tr225;
		case 93: goto tr226;
		case 101: goto tr227;
		case 120: goto tr228;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr216;
	} else if ( (*p) >= 9 )
		goto tr222;
	goto tr134;
case 64:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto tr229;
	goto tr1;
case 65:
	switch( (*p) ) {
		case 32: goto tr218;
		case 44: goto tr219;
		case 47: goto tr220;
		case 93: goto tr221;
		case 101: goto tr227;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr229;
	} else if ( (*p) >= 9 )
		goto tr218;
	goto tr134;
case 66:
	if ( (*p) == 45 )
		goto tr214;
	if ( 48 <= (*p) && (*p) <= 57 )
		goto tr217;
	goto tr1;
case 67:
	switch( (*p) ) {
		case 32: goto tr222;
		case 44: goto tr223;
		case 46: goto tr224;
		case 47: goto tr225;
		case 93: goto tr226;
		case 101: goto tr227;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr216;
	} else if ( (*p) >= 9 )
		goto tr222;
	goto tr134;
case 68:
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr230;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr232;
	} else
		goto tr231;
	goto tr1;
case 69:
	switch( (*p) ) {
		case 32: goto tr233;
		case 44: goto tr234;
		case 47: goto tr235;
		case 93: goto tr236;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr233;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 70 ) {
			if ( 97 <= (*p) && (*p) <= 102 )
				goto tr232;
		} else if ( (*p) >= 65 )
			goto tr231;
	} else
		goto tr230;
	goto tr134;
case 70:
	if ( (*p) == 47 )
		goto tr237;
	goto tr1;
case 71:
	switch( (*p) ) {
		case 32: goto tr139;
		case 44: goto tr113;
		case 47: goto tr140;
		case 93: goto tr123;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr139;
	goto tr134;
case 72:
	if ( (*p) == 97 )
		goto tr238;
	goto tr1;
case 73:
	if ( (*p) == 108 )
		goto tr239;
	goto tr1;
case 74:
	if ( (*p) == 115 )
		goto tr240;
	goto tr1;
case 75:
	if ( (*p) == 101 )
		goto tr241;
	goto tr1;
case 76:
	switch( (*p) ) {
		case 32: goto tr242;
		case 44: goto tr243;
		case 47: goto tr244;
		case 93: goto tr245;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr242;
	goto tr134;
case 77:
	if ( (*p) == 117 )
		goto tr246;
	goto tr1;
case 78:
	if ( (*p) == 108 )
		goto tr247;
	goto tr1;
case 79:
	if ( (*p) == 108 )
		goto tr248;
	goto tr1;
case 80:
	switch( (*p) ) {
		case 32: goto tr249;
		case 44: goto tr250;
		case 47: goto tr251;
		case 93: goto tr252;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr249;
	goto tr134;
case 81:
	if ( (*p) == 114 )
		goto tr253;
	goto tr1;
case 82:
	if ( (*p) == 117 )
		goto tr254;
	goto tr1;
case 83:
	if ( (*p) == 101 )
		goto tr255;
	goto tr1;
case 84:
	switch( (*p) ) {
		case 32: goto tr256;
		case 44: goto tr257;
		case 47: goto tr258;
		case 93: goto tr259;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr256;
	goto tr134;
case 85:
	if ( (*p) == 123 )
		goto tr260;
	goto tr1;
case 86:
	switch( (*p) ) {
		case 32: goto tr261;
		case 34: goto tr262;
		case 47: goto tr263;
		case 95: goto tr264;
		case 125: goto tr265;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr261;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr264;
		} else if ( (*p) >= 65 )
			goto tr264;
	} else
		goto tr264;
	goto tr1;
case 87:
	switch( (*p) ) {
		case 34: goto tr267;
		case 92: goto tr268;
	}
	goto tr266;
case 88:
	switch( (*p) ) {
		case 34: goto tr270;
		case 92: goto tr271;
	}
	goto tr269;
case 89:
	switch( (*p) ) {
		case 32: goto tr272;
		case 40: goto tr273;
		case 47: goto tr274;
		case 58: goto tr275;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr272;
	goto tr1;
case 90:
	switch( (*p) ) {
		case 32: goto tr276;
		case 40: goto tr277;
		case 47: goto tr278;
		case 58: goto tr279;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr276;
	goto tr1;
case 91:
	switch( (*p) ) {
		case 32: goto tr277;
		case 47: goto tr280;
		case 95: goto tr281;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr277;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr281;
		} else if ( (*p) >= 65 )
			goto tr281;
	} else
		goto tr281;
	goto tr1;
case 92:
	if ( (*p) == 47 )
		goto tr282;
	goto tr1;
case 93:
	switch( (*p) ) {
		case 32: goto tr283;
		case 41: goto tr284;
		case 44: goto tr285;
		case 47: goto tr286;
		case 95: goto tr287;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr283;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr287;
		} else if ( (*p) >= 65 )
			goto tr287;
	} else
		goto tr287;
	goto tr1;
case 94:
	switch( (*p) ) {
		case 32: goto tr288;
		case 41: goto tr289;
		case 44: goto tr290;
		case 47: goto tr291;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr288;
	goto tr1;
case 95:
	switch( (*p) ) {
		case 32: goto tr289;
		case 47: goto tr292;
		case 58: goto tr279;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr289;
	goto tr1;
case 96:
	if ( (*p) == 47 )
		goto tr293;
	goto tr1;
case 97:
	switch( (*p) ) {
		case 32: goto tr279;
		case 34: goto tr294;
		case 37: goto tr295;
		case 43: goto tr296;
		case 45: goto tr297;
		case 46: goto tr298;
		case 47: goto tr299;
		case 48: goto tr300;
		case 91: goto tr302;
		case 102: goto tr303;
		case 110: goto tr304;
		case 116: goto tr305;
		case 123: goto tr306;
	}
	if ( (*p) > 10 ) {
		if ( 49 <= (*p) && (*p) <= 57 )
			goto tr301;
	} else if ( (*p) >= 9 )
		goto tr279;
	goto tr1;
case 98:
	switch( (*p) ) {
		case 34: goto tr308;
		case 92: goto tr309;
	}
	goto tr307;
case 99:
	switch( (*p) ) {
		case 34: goto tr311;
		case 92: goto tr312;
	}
	goto tr310;
case 100:
	switch( (*p) ) {
		case 32: goto tr313;
		case 44: goto tr314;
		case 47: goto tr315;
		case 125: goto tr316;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr313;
	goto tr134;
case 101:
	switch( (*p) ) {
		case 32: goto tr317;
		case 44: goto tr261;
		case 47: goto tr318;
		case 125: goto tr265;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr317;
	goto tr1;
case 102:
	if ( (*p) == 47 )
		goto tr319;
	goto tr1;
case 165:
	goto tr472;
case 103:
	if ( (*p) == 92 )
		goto tr312;
	goto tr310;
case 104:
	switch( (*p) ) {
		case 32: goto tr320;
		case 37: goto tr321;
		case 43: goto tr322;
		case 47: goto tr323;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr320;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr326;
		} else if ( (*p) >= 65 )
			goto tr325;
	} else
		goto tr324;
	goto tr1;
case 105:
	switch( (*p) ) {
		case 32: goto tr327;
		case 44: goto tr328;
		case 47: goto tr329;
		case 125: goto tr330;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr327;
	goto tr134;
case 106:
	switch( (*p) ) {
		case 43: goto tr331;
		case 47: goto tr332;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr333;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr335;
	} else
		goto tr334;
	goto tr1;
case 107:
	switch( (*p) ) {
		case 43: goto tr336;
		case 47: goto tr337;
		case 61: goto tr339;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr338;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr341;
	} else
		goto tr340;
	goto tr1;
case 108:
	switch( (*p) ) {
		case 43: goto tr342;
		case 47: goto tr343;
		case 61: goto tr345;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr344;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr347;
	} else
		goto tr346;
	goto tr1;
case 109:
	switch( (*p) ) {
		case 32: goto tr348;
		case 37: goto tr349;
		case 43: goto tr350;
		case 47: goto tr351;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr348;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr354;
		} else if ( (*p) >= 65 )
			goto tr353;
	} else
		goto tr352;
	goto tr46;
case 110:
	switch( (*p) ) {
		case 43: goto tr331;
		case 47: goto tr355;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr333;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr335;
	} else
		goto tr334;
	goto tr1;
case 111:
	switch( (*p) ) {
		case 32: goto tr320;
		case 37: goto tr321;
		case 43: goto tr356;
		case 47: goto tr357;
		case 61: goto tr339;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr320;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr360;
		} else if ( (*p) >= 65 )
			goto tr359;
	} else
		goto tr358;
	goto tr1;
case 112:
	switch( (*p) ) {
		case 43: goto tr361;
		case 47: goto tr362;
		case 61: goto tr345;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr363;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr365;
	} else
		goto tr364;
	goto tr1;
case 113:
	switch( (*p) ) {
		case 32: goto tr348;
		case 37: goto tr349;
		case 43: goto tr366;
		case 47: goto tr367;
		case 61: goto tr339;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr348;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr370;
		} else if ( (*p) >= 65 )
			goto tr369;
	} else
		goto tr368;
	goto tr46;
case 114:
	switch( (*p) ) {
		case 43: goto tr361;
		case 47: goto tr371;
		case 61: goto tr345;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr363;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto tr365;
	} else
		goto tr364;
	goto tr1;
case 115:
	switch( (*p) ) {
		case 32: goto tr348;
		case 37: goto tr349;
		case 43: goto tr372;
		case 47: goto tr373;
		case 61: goto tr339;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr348;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr376;
		} else if ( (*p) >= 65 )
			goto tr375;
	} else
		goto tr374;
	goto tr46;
case 116:
	if ( (*p) == 61 )
		goto tr377;
	goto tr1;
case 117:
	switch( (*p) ) {
		case 32: goto tr378;
		case 37: goto tr379;
		case 43: goto tr380;
		case 47: goto tr381;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr378;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr384;
		} else if ( (*p) >= 65 )
			goto tr383;
	} else
		goto tr382;
	goto tr46;
case 118:
	switch( (*p) ) {
		case 32: goto tr385;
		case 37: goto tr386;
		case 43: goto tr387;
		case 47: goto tr388;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr385;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr391;
		} else if ( (*p) >= 65 )
			goto tr390;
	} else
		goto tr389;
	goto tr46;
case 119:
	switch( (*p) ) {
		case 46: goto tr392;
		case 48: goto tr393;
	}
	if ( 49 <= (*p) && (*p) <= 57 )
		goto tr394;
	goto tr1;
case 120:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto tr395;
	goto tr1;
case 121:
	switch( (*p) ) {
		case 32: goto tr396;
		case 44: goto tr397;
		case 47: goto tr398;
		case 125: goto tr399;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr395;
	} else if ( (*p) >= 9 )
		goto tr396;
	goto tr134;
case 122:
	switch( (*p) ) {
		case 32: goto tr400;
		case 44: goto tr401;
		case 46: goto tr402;
		case 47: goto tr403;
		case 101: goto tr404;
		case 120: goto tr405;
		case 125: goto tr406;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr394;
	} else if ( (*p) >= 9 )
		goto tr400;
	goto tr134;
case 123:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto tr407;
	goto tr1;
case 124:
	switch( (*p) ) {
		case 32: goto tr396;
		case 44: goto tr397;
		case 47: goto tr398;
		case 101: goto tr404;
		case 125: goto tr399;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr407;
	} else if ( (*p) >= 9 )
		goto tr396;
	goto tr134;
case 125:
	if ( (*p) == 45 )
		goto tr392;
	if ( 48 <= (*p) && (*p) <= 57 )
		goto tr395;
	goto tr1;
case 126:
	switch( (*p) ) {
		case 32: goto tr400;
		case 44: goto tr401;
		case 46: goto tr402;
		case 47: goto tr403;
		case 101: goto tr404;
		case 125: goto tr406;
	}
	if ( (*p) > 10 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr394;
	} else if ( (*p) >= 9 )
		goto tr400;
	goto tr134;
case 127:
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr408;
	} else if ( (*p) > 70 ) {
		if ( 97 <= (*p) && (*p) <= 102 )
			goto tr410;
	} else
		goto tr409;
	goto tr1;
case 128:
	switch( (*p) ) {
		case 32: goto tr411;
		case 44: goto tr412;
		case 47: goto tr413;
		case 125: goto tr414;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr411;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 70 ) {
			if ( 97 <= (*p) && (*p) <= 102 )
				goto tr410;
		} else if ( (*p) >= 65 )
			goto tr409;
	} else
		goto tr408;
	goto tr134;
case 129:
	if ( (*p) == 47 )
		goto tr415;
	goto tr1;
case 130:
	switch( (*p) ) {
		case 32: goto tr317;
		case 44: goto tr261;
		case 47: goto tr318;
		case 125: goto tr265;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr317;
	goto tr134;
case 131:
	if ( (*p) == 97 )
		goto tr416;
	goto tr1;
case 132:
	if ( (*p) == 108 )
		goto tr417;
	goto tr1;
case 133:
	if ( (*p) == 115 )
		goto tr418;
	goto tr1;
case 134:
	if ( (*p) == 101 )
		goto tr419;
	goto tr1;
case 135:
	switch( (*p) ) {
		case 32: goto tr420;
		case 44: goto tr421;
		case 47: goto tr422;
		case 125: goto tr423;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr420;
	goto tr134;
case 136:
	if ( (*p) == 117 )
		goto tr424;
	goto tr1;
case 137:
	if ( (*p) == 108 )
		goto tr425;
	goto tr1;
case 138:
	if ( (*p) == 108 )
		goto tr426;
	goto tr1;
case 139:
	switch( (*p) ) {
		case 32: goto tr427;
		case 44: goto tr428;
		case 47: goto tr429;
		case 125: goto tr430;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr427;
	goto tr134;
case 140:
	if ( (*p) == 114 )
		goto tr431;
	goto tr1;
case 141:
	if ( (*p) == 117 )
		goto tr432;
	goto tr1;
case 142:
	if ( (*p) == 101 )
		goto tr433;
	goto tr1;
case 143:
	switch( (*p) ) {
		case 32: goto tr434;
		case 44: goto tr435;
		case 47: goto tr436;
		case 125: goto tr437;
	}
	if ( 9 <= (*p) && (*p) <= 10 )
		goto tr434;
	goto tr134;
case 144:
	switch( (*p) ) {
		case 32: goto tr290;
		case 41: goto tr289;
		case 47: goto tr438;
		case 95: goto tr281;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr290;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr281;
		} else if ( (*p) >= 65 )
			goto tr281;
	} else
		goto tr281;
	goto tr1;
case 145:
	if ( (*p) == 47 )
		goto tr439;
	goto tr1;
case 146:
	if ( (*p) == 47 )
		goto tr440;
	goto tr1;
case 147:
	if ( (*p) == 47 )
		goto tr441;
	goto tr1;
case 148:
	if ( (*p) == 92 )
		goto tr271;
	goto tr269;
case 149:
	if ( (*p) == 47 )
		goto tr442;
	goto tr1;
case 150:
	switch( (*p) ) {
		case 32: goto tr443;
		case 40: goto tr444;
		case 47: goto tr445;
		case 58: goto tr447;
		case 95: goto tr446;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 10 )
			goto tr443;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto tr446;
		} else if ( (*p) >= 65 )
			goto tr446;
	} else
		goto tr446;
	goto tr1;
	}

	tr1: cs = 0; goto _again;
	tr46: cs = 0; goto f23;
	tr134: cs = 0; goto f60;
	tr448: cs = 0; goto f90;
	tr451: cs = 0; goto f91;
	tr471: cs = 0; goto f92;
	tr472: cs = 0; goto f93;
	tr0: cs = 1; goto _again;
	tr99: cs = 1; goto f11;
	tr2: cs = 2; goto f0;
	tr18: cs = 3; goto _again;
	tr15: cs = 3; goto f8;
	tr453: cs = 4; goto _again;
	tr450: cs = 4; goto f61;
	tr455: cs = 4; goto f63;
	tr457: cs = 4; goto f65;
	tr460: cs = 4; goto f67;
	tr464: cs = 4; goto f69;
	tr466: cs = 4; goto f71;
	tr468: cs = 4; goto f73;
	tr470: cs = 4; goto f75;
	tr20: cs = 5; goto _again;
	tr17: cs = 5; goto f8;
	tr22: cs = 6; goto _again;
	tr3: cs = 6; goto f1;
	tr47: cs = 6; goto f24;
	tr77: cs = 6; goto f41;
	tr84: cs = 6; goto f47;
	tr24: cs = 7; goto f12;
	tr26: cs = 7; goto f14;
	tr27: cs = 7; goto f15;
	tr28: cs = 7; goto f16;
	tr49: cs = 7; goto f25;
	tr51: cs = 7; goto f27;
	tr52: cs = 7; goto f28;
	tr53: cs = 7; goto f29;
	tr79: cs = 7; goto f42;
	tr81: cs = 7; goto f44;
	tr82: cs = 7; goto f45;
	tr83: cs = 7; goto f46;
	tr86: cs = 7; goto f48;
	tr88: cs = 7; goto f50;
	tr89: cs = 7; goto f51;
	tr90: cs = 7; goto f52;
	tr29: cs = 8; goto f17;
	tr30: cs = 8; goto f18;
	tr31: cs = 8; goto f19;
	tr32: cs = 8; goto f20;
	tr33: cs = 8; goto f21;
	tr34: cs = 9; goto f17;
	tr35: cs = 9; goto f18;
	tr36: cs = 9; goto f19;
	tr38: cs = 9; goto f20;
	tr39: cs = 9; goto f21;
	tr40: cs = 10; goto f17;
	tr41: cs = 10; goto f18;
	tr42: cs = 10; goto f19;
	tr44: cs = 10; goto f20;
	tr45: cs = 10; goto f21;
	tr25: cs = 11; goto f13;
	tr50: cs = 11; goto f26;
	tr80: cs = 11; goto f43;
	tr87: cs = 11; goto f49;
	tr54: cs = 12; goto f30;
	tr55: cs = 13; goto f12;
	tr57: cs = 13; goto f14;
	tr58: cs = 13; goto f15;
	tr59: cs = 13; goto f16;
	tr65: cs = 13; goto f31;
	tr67: cs = 13; goto f33;
	tr68: cs = 13; goto f34;
	tr69: cs = 13; goto f35;
	tr71: cs = 13; goto f36;
	tr73: cs = 13; goto f38;
	tr74: cs = 13; goto f39;
	tr75: cs = 13; goto f40;
	tr60: cs = 14; goto f17;
	tr61: cs = 14; goto f18;
	tr62: cs = 14; goto f19;
	tr63: cs = 14; goto f20;
	tr64: cs = 14; goto f21;
	tr56: cs = 15; goto f13;
	tr66: cs = 15; goto f32;
	tr72: cs = 15; goto f37;
	tr70: cs = 16; goto f30;
	tr37: cs = 17; goto f22;
	tr76: cs = 18; goto f22;
	tr43: cs = 19; goto f22;
	tr4: cs = 20; goto f2;
	tr5: cs = 20; goto f3;
	tr91: cs = 21; goto _again;
	tr6: cs = 21; goto f4;
	tr459: cs = 22; goto _again;
	tr461: cs = 23; goto _again;
	tr462: cs = 24; goto _again;
	tr7: cs = 25; goto _again;
	tr11: cs = 26; goto f0;
	tr100: cs = 27; goto _again;
	tr101: cs = 28; goto _again;
	tr102: cs = 29; goto _again;
	tr12: cs = 30; goto f0;
	tr104: cs = 31; goto _again;
	tr105: cs = 32; goto _again;
	tr13: cs = 33; goto f0;
	tr107: cs = 34; goto _again;
	tr108: cs = 35; goto _again;
	tr110: cs = 36; goto _again;
	tr113: cs = 38; goto _again;
	tr237: cs = 38; goto f11;
	tr112: cs = 38; goto f58;
	tr136: cs = 38; goto f61;
	tr150: cs = 38; goto f63;
	tr219: cs = 38; goto f65;
	tr223: cs = 38; goto f67;
	tr234: cs = 38; goto f69;
	tr243: cs = 38; goto f71;
	tr250: cs = 38; goto f73;
	tr257: cs = 38; goto f75;
	tr114: cs = 39; goto f0;
	tr131: cs = 40; goto _again;
	tr128: cs = 40; goto f8;
	tr129: cs = 41; goto f9;
	tr132: cs = 41; goto f10;
	tr139: cs = 42; goto _again;
	tr141: cs = 42; goto f11;
	tr135: cs = 42; goto f61;
	tr149: cs = 42; goto f63;
	tr218: cs = 42; goto f65;
	tr222: cs = 42; goto f67;
	tr233: cs = 42; goto f69;
	tr242: cs = 42; goto f71;
	tr249: cs = 42; goto f73;
	tr256: cs = 42; goto f75;
	tr140: cs = 43; goto _again;
	tr137: cs = 43; goto f61;
	tr151: cs = 43; goto f63;
	tr220: cs = 43; goto f65;
	tr225: cs = 43; goto f67;
	tr235: cs = 43; goto f69;
	tr244: cs = 43; goto f71;
	tr251: cs = 43; goto f73;
	tr258: cs = 43; goto f75;
	tr133: cs = 44; goto _again;
	tr130: cs = 44; goto f8;
	tr142: cs = 45; goto _again;
	tr115: cs = 45; goto f1;
	tr170: cs = 45; goto f24;
	tr200: cs = 45; goto f41;
	tr207: cs = 45; goto f47;
	tr143: cs = 46; goto _again;
	tr171: cs = 46; goto f24;
	tr201: cs = 46; goto f41;
	tr208: cs = 46; goto f47;
	tr144: cs = 47; goto f12;
	tr146: cs = 47; goto f14;
	tr147: cs = 47; goto f15;
	tr148: cs = 47; goto f16;
	tr172: cs = 47; goto f25;
	tr174: cs = 47; goto f27;
	tr175: cs = 47; goto f28;
	tr176: cs = 47; goto f29;
	tr202: cs = 47; goto f42;
	tr204: cs = 47; goto f44;
	tr205: cs = 47; goto f45;
	tr206: cs = 47; goto f46;
	tr209: cs = 47; goto f48;
	tr211: cs = 47; goto f50;
	tr212: cs = 47; goto f51;
	tr213: cs = 47; goto f52;
	tr153: cs = 48; goto f17;
	tr154: cs = 48; goto f18;
	tr155: cs = 48; goto f19;
	tr156: cs = 48; goto f20;
	tr157: cs = 48; goto f21;
	tr158: cs = 49; goto f17;
	tr159: cs = 49; goto f18;
	tr160: cs = 49; goto f19;
	tr162: cs = 49; goto f20;
	tr163: cs = 49; goto f21;
	tr164: cs = 50; goto f17;
	tr165: cs = 50; goto f18;
	tr166: cs = 50; goto f19;
	tr168: cs = 50; goto f20;
	tr169: cs = 50; goto f21;
	tr145: cs = 51; goto f13;
	tr173: cs = 51; goto f26;
	tr203: cs = 51; goto f43;
	tr210: cs = 51; goto f49;
	tr177: cs = 52; goto f30;
	tr178: cs = 53; goto f12;
	tr180: cs = 53; goto f14;
	tr181: cs = 53; goto f15;
	tr182: cs = 53; goto f16;
	tr188: cs = 53; goto f31;
	tr190: cs = 53; goto f33;
	tr191: cs = 53; goto f34;
	tr192: cs = 53; goto f35;
	tr194: cs = 53; goto f36;
	tr196: cs = 53; goto f38;
	tr197: cs = 53; goto f39;
	tr198: cs = 53; goto f40;
	tr183: cs = 54; goto f17;
	tr184: cs = 54; goto f18;
	tr185: cs = 54; goto f19;
	tr186: cs = 54; goto f20;
	tr187: cs = 54; goto f21;
	tr179: cs = 55; goto f13;
	tr189: cs = 55; goto f32;
	tr195: cs = 55; goto f37;
	tr193: cs = 56; goto f30;
	tr161: cs = 57; goto f22;
	tr199: cs = 58; goto f22;
	tr167: cs = 59; goto f22;
	tr116: cs = 60; goto f2;
	tr117: cs = 60; goto f3;
	tr214: cs = 61; goto _again;
	tr118: cs = 61; goto f4;
	tr217: cs = 62; goto _again;
	tr120: cs = 63; goto f5;
	tr215: cs = 63; goto f53;
	tr224: cs = 64; goto _again;
	tr229: cs = 65; goto _again;
	tr227: cs = 66; goto _again;
	tr121: cs = 67; goto f5;
	tr216: cs = 67; goto f53;
	tr228: cs = 68; goto _again;
	tr230: cs = 69; goto f54;
	tr231: cs = 69; goto f55;
	tr232: cs = 69; goto f56;
	tr119: cs = 70; goto _again;
	tr122: cs = 71; goto f6;
	tr127: cs = 71; goto f7;
	tr124: cs = 72; goto f0;
	tr238: cs = 73; goto _again;
	tr239: cs = 74; goto _again;
	tr240: cs = 75; goto _again;
	tr241: cs = 76; goto _again;
	tr125: cs = 77; goto f0;
	tr246: cs = 78; goto _again;
	tr247: cs = 79; goto _again;
	tr248: cs = 80; goto _again;
	tr126: cs = 81; goto f0;
	tr253: cs = 82; goto _again;
	tr254: cs = 83; goto _again;
	tr255: cs = 84; goto _again;
	tr261: cs = 86; goto _again;
	tr442: cs = 86; goto f11;
	tr314: cs = 86; goto f61;
	tr328: cs = 86; goto f63;
	tr397: cs = 86; goto f65;
	tr401: cs = 86; goto f67;
	tr412: cs = 86; goto f69;
	tr421: cs = 86; goto f71;
	tr428: cs = 86; goto f73;
	tr435: cs = 86; goto f75;
	tr260: cs = 86; goto f77;
	tr262: cs = 87; goto _again;
	tr269: cs = 88; goto _again;
	tr266: cs = 88; goto f8;
	tr267: cs = 89; goto f9;
	tr270: cs = 89; goto f10;
	tr276: cs = 90; goto _again;
	tr441: cs = 90; goto f11;
	tr272: cs = 90; goto f79;
	tr443: cs = 90; goto f89;
	tr277: cs = 91; goto _again;
	tr282: cs = 91; goto f11;
	tr273: cs = 91; goto f79;
	tr444: cs = 91; goto f89;
	tr280: cs = 92; goto _again;
	tr287: cs = 93; goto _again;
	tr281: cs = 93; goto f8;
	tr288: cs = 94; goto _again;
	tr440: cs = 94; goto f11;
	tr283: cs = 94; goto f80;
	tr289: cs = 95; goto _again;
	tr293: cs = 95; goto f11;
	tr284: cs = 95; goto f80;
	tr292: cs = 96; goto _again;
	tr279: cs = 97; goto _again;
	tr415: cs = 97; goto f11;
	tr275: cs = 97; goto f79;
	tr447: cs = 97; goto f89;
	tr294: cs = 98; goto f0;
	tr310: cs = 99; goto _again;
	tr307: cs = 99; goto f8;
	tr308: cs = 100; goto f9;
	tr311: cs = 100; goto f10;
	tr317: cs = 101; goto _again;
	tr319: cs = 101; goto f11;
	tr313: cs = 101; goto f61;
	tr327: cs = 101; goto f63;
	tr396: cs = 101; goto f65;
	tr400: cs = 101; goto f67;
	tr411: cs = 101; goto f69;
	tr420: cs = 101; goto f71;
	tr427: cs = 101; goto f73;
	tr434: cs = 101; goto f75;
	tr318: cs = 102; goto _again;
	tr315: cs = 102; goto f61;
	tr329: cs = 102; goto f63;
	tr398: cs = 102; goto f65;
	tr403: cs = 102; goto f67;
	tr413: cs = 102; goto f69;
	tr422: cs = 102; goto f71;
	tr429: cs = 102; goto f73;
	tr436: cs = 102; goto f75;
	tr312: cs = 103; goto _again;
	tr309: cs = 103; goto f8;
	tr320: cs = 104; goto _again;
	tr295: cs = 104; goto f1;
	tr348: cs = 104; goto f24;
	tr378: cs = 104; goto f41;
	tr385: cs = 104; goto f47;
	tr321: cs = 105; goto _again;
	tr349: cs = 105; goto f24;
	tr379: cs = 105; goto f41;
	tr386: cs = 105; goto f47;
	tr322: cs = 106; goto f12;
	tr324: cs = 106; goto f14;
	tr325: cs = 106; goto f15;
	tr326: cs = 106; goto f16;
	tr350: cs = 106; goto f25;
	tr352: cs = 106; goto f27;
	tr353: cs = 106; goto f28;
	tr354: cs = 106; goto f29;
	tr380: cs = 106; goto f42;
	tr382: cs = 106; goto f44;
	tr383: cs = 106; goto f45;
	tr384: cs = 106; goto f46;
	tr387: cs = 106; goto f48;
	tr389: cs = 106; goto f50;
	tr390: cs = 106; goto f51;
	tr391: cs = 106; goto f52;
	tr331: cs = 107; goto f17;
	tr332: cs = 107; goto f18;
	tr333: cs = 107; goto f19;
	tr334: cs = 107; goto f20;
	tr335: cs = 107; goto f21;
	tr336: cs = 108; goto f17;
	tr337: cs = 108; goto f18;
	tr338: cs = 108; goto f19;
	tr340: cs = 108; goto f20;
	tr341: cs = 108; goto f21;
	tr342: cs = 109; goto f17;
	tr343: cs = 109; goto f18;
	tr344: cs = 109; goto f19;
	tr346: cs = 109; goto f20;
	tr347: cs = 109; goto f21;
	tr323: cs = 110; goto f13;
	tr351: cs = 110; goto f26;
	tr381: cs = 110; goto f43;
	tr388: cs = 110; goto f49;
	tr355: cs = 111; goto f30;
	tr356: cs = 112; goto f12;
	tr358: cs = 112; goto f14;
	tr359: cs = 112; goto f15;
	tr360: cs = 112; goto f16;
	tr366: cs = 112; goto f31;
	tr368: cs = 112; goto f33;
	tr369: cs = 112; goto f34;
	tr370: cs = 112; goto f35;
	tr372: cs = 112; goto f36;
	tr374: cs = 112; goto f38;
	tr375: cs = 112; goto f39;
	tr376: cs = 112; goto f40;
	tr361: cs = 113; goto f17;
	tr362: cs = 113; goto f18;
	tr363: cs = 113; goto f19;
	tr364: cs = 113; goto f20;
	tr365: cs = 113; goto f21;
	tr357: cs = 114; goto f13;
	tr367: cs = 114; goto f32;
	tr373: cs = 114; goto f37;
	tr371: cs = 115; goto f30;
	tr339: cs = 116; goto f22;
	tr377: cs = 117; goto f22;
	tr345: cs = 118; goto f22;
	tr296: cs = 119; goto f2;
	tr297: cs = 119; goto f3;
	tr392: cs = 120; goto _again;
	tr298: cs = 120; goto f4;
	tr395: cs = 121; goto _again;
	tr300: cs = 122; goto f5;
	tr393: cs = 122; goto f53;
	tr402: cs = 123; goto _again;
	tr407: cs = 124; goto _again;
	tr404: cs = 125; goto _again;
	tr301: cs = 126; goto f5;
	tr394: cs = 126; goto f53;
	tr405: cs = 127; goto _again;
	tr408: cs = 128; goto f54;
	tr409: cs = 128; goto f55;
	tr410: cs = 128; goto f56;
	tr299: cs = 129; goto _again;
	tr302: cs = 130; goto f6;
	tr306: cs = 130; goto f7;
	tr303: cs = 131; goto f0;
	tr416: cs = 132; goto _again;
	tr417: cs = 133; goto _again;
	tr418: cs = 134; goto _again;
	tr419: cs = 135; goto _again;
	tr304: cs = 136; goto f0;
	tr424: cs = 137; goto _again;
	tr425: cs = 138; goto _again;
	tr426: cs = 139; goto _again;
	tr305: cs = 140; goto f0;
	tr431: cs = 141; goto _again;
	tr432: cs = 142; goto _again;
	tr433: cs = 143; goto _again;
	tr290: cs = 144; goto _again;
	tr439: cs = 144; goto f11;
	tr285: cs = 144; goto f80;
	tr438: cs = 145; goto _again;
	tr291: cs = 146; goto _again;
	tr286: cs = 146; goto f80;
	tr278: cs = 147; goto _again;
	tr274: cs = 147; goto f79;
	tr445: cs = 147; goto f89;
	tr271: cs = 148; goto _again;
	tr268: cs = 148; goto f8;
	tr263: cs = 149; goto _again;
	tr446: cs = 150; goto _again;
	tr264: cs = 150; goto f8;
	tr16: cs = 151; goto f9;
	tr19: cs = 151; goto f10;
	tr452: cs = 152; goto _again;
	tr21: cs = 152; goto f11;
	tr449: cs = 152; goto f61;
	tr454: cs = 152; goto f63;
	tr456: cs = 152; goto f65;
	tr458: cs = 152; goto f67;
	tr463: cs = 152; goto f69;
	tr465: cs = 152; goto f71;
	tr467: cs = 152; goto f73;
	tr469: cs = 152; goto f75;
	tr23: cs = 153; goto _again;
	tr48: cs = 153; goto f24;
	tr78: cs = 153; goto f41;
	tr85: cs = 153; goto f47;
	tr94: cs = 154; goto _again;
	tr8: cs = 155; goto f5;
	tr92: cs = 155; goto f53;
	tr95: cs = 156; goto _again;
	tr9: cs = 157; goto f5;
	tr93: cs = 157; goto f53;
	tr96: cs = 158; goto f54;
	tr97: cs = 158; goto f55;
	tr98: cs = 158; goto f56;
	tr10: cs = 159; goto f6;
	tr14: cs = 159; goto f7;
	tr103: cs = 160; goto _again;
	tr106: cs = 161; goto _again;
	tr109: cs = 162; goto _again;
	tr111: cs = 163; goto f57;
	tr123: cs = 164; goto f59;
	tr138: cs = 164; goto f62;
	tr152: cs = 164; goto f64;
	tr221: cs = 164; goto f66;
	tr226: cs = 164; goto f68;
	tr236: cs = 164; goto f70;
	tr245: cs = 164; goto f72;
	tr252: cs = 164; goto f74;
	tr259: cs = 164; goto f76;
	tr265: cs = 165; goto f78;
	tr316: cs = 165; goto f81;
	tr330: cs = 165; goto f82;
	tr399: cs = 165; goto f83;
	tr406: cs = 165; goto f84;
	tr414: cs = 165; goto f85;
	tr423: cs = 165; goto f86;
	tr430: cs = 165; goto f87;
	tr437: cs = 165; goto f88;

f77:
#line 129 "ejson.rl"
	{ d->open_object(d); }
	goto _again;
f58:
#line 131 "ejson.rl"
	{ d->open_array(d); }
	goto _again;
f79:
#line 133 "ejson.rl"
	{ d->set_name(d, &v); }
	goto _again;
f61:
#line 135 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_string, &v); }
	goto _again;
f75:
#line 139 "ejson.rl"
	{ v.u.v_bool = 1; d->set_value(d, ejson_driver_type_bool, &v); }
	goto _again;
f71:
#line 140 "ejson.rl"
	{ v.u.v_bool = 0; d->set_value(d, ejson_driver_type_bool, &v); }
	goto _again;
f73:
#line 141 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_null, NULL); }
	goto _again;
f63:
#line 168 "ejson.rl"
	{
			if (base64_hold && d->add_data)
				d->add_data(d, base64, base64_hold);
			if (d->close_data) d->close_data(d);
		}
	goto _again;
f57:
#line 173 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f11:
#line 174 "ejson.rl"
	{ p--;{
			// prepush thing
			if (top == stack_size) {
				stack_size += 8;
				stack = realloc(stack, stack_size * sizeof(int));
			}
		{stack[top++] = cs; cs = 36; goto _again;}} }
	goto _again;
f8:
#line 187 "ejson.rl"
	{ v.u.v_str.start = v.u.v_str.end = p; }
	goto _again;
f10:
#line 188 "ejson.rl"
	{ v.u.v_str.end = p; }
	goto _again;
f53:
#line 198 "ejson.rl"
	{ v.u.v_int = (v.u.v_int * 10) + ((*p) - '0'); }
	goto _again;
f54:
#line 208 "ejson.rl"
	{ v.u.v_int = (v.u.v_int << 4) | ((*p) - '0'); }
	goto _again;
f56:
#line 209 "ejson.rl"
	{ v.u.v_int = (v.u.v_int << 4) | ((*p) - 'a' + 0xa); }
	goto _again;
f55:
#line 210 "ejson.rl"
	{ v.u.v_int = (v.u.v_int << 4) | ((*p) - 'A' + 0xa); }
	goto _again;
f20:
#line 247 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'A'); }
	goto _again;
f21:
#line 248 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'a' + 26 ); }
	goto _again;
f19:
#line 249 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - '0' + 52 ); }
	goto _again;
f17:
#line 250 "ejson.rl"
	{ b64 = (b64 << 6) | 62; }
	goto _again;
f18:
#line 251 "ejson.rl"
	{ b64 = (b64 << 6) | 63; }
	goto _again;
f22:
#line 253 "ejson.rl"
	{ b64 = (b64 << 6); }
	goto _again;
f23:
#line 268 "ejson.rl"
	{ printf("### base64 Error : '%s'\n", p); }
	goto _again;
f0:
#line 285 "ejson.rl"
	{ _value_start = p; }
	goto _again;
f60:
#line 286 "ejson.rl"
	{ printf("### Value[%d] Error : '%s'\n", top, _value_start); }
	goto _again;
f92:
#line 293 "ejson.rl"
	{ printf("### Array[%d] Error : '%s'\n", top, p); }
	goto _again;
f93:
#line 306 "ejson.rl"
	{ printf("### Object[%d] Error : '%s'\n", top, p); }
	goto _again;
f91:
#line 310 "ejson.rl"
	{ printf("### ejson Error : '%s'\n", p); }
	goto _again;
f78:
#line 130 "ejson.rl"
	{ d->close_object(d); }
#line 305 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f59:
#line 132 "ejson.rl"
	{ d->close_array(d); }
#line 292 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f30:
#line 174 "ejson.rl"
	{ p--;{
			// prepush thing
			if (top == stack_size) {
				stack_size += 8;
				stack = realloc(stack, stack_size * sizeof(int));
			}
		{stack[top++] = cs; cs = 36; goto _again;}} }
#line 251 "ejson.rl"
	{ b64 = (b64 << 6) | 63; }
	goto _again;
f9:
#line 187 "ejson.rl"
	{ v.u.v_str.start = v.u.v_str.end = p; }
#line 188 "ejson.rl"
	{ v.u.v_str.end = p; }
	goto _again;
f89:
#line 188 "ejson.rl"
	{ v.u.v_str.end = p; }
#line 133 "ejson.rl"
	{ d->set_name(d, &v); }
	goto _again;
f80:
#line 188 "ejson.rl"
	{ v.u.v_str.end = p; }
#line 134 "ejson.rl"
	{ if (d->add_flag) d->add_flag(d, &v); }
	goto _again;
f67:
#line 199 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 136 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_integer, &v); }
	goto _again;
f69:
#line 199 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 138 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_hex, &v); }
	goto _again;
f65:
#line 219 "ejson.rl"
	{ 
			int l = p - float_start;
			if (l >= sizeof(float_value)) {
				l = sizeof(float_value)-1;
			}
			memcpy(float_value, float_start, l);
			float_value[l] = 0;
			double lf = 0.0d; 
			sscanf(float_value, "%lg", &lf); 
			v.u.v_float = lf;
			float_start = NULL;
		}
#line 137 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_float, &v); }
	goto _again;
f24:
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
	goto _again;
f47:
#line 261 "ejson.rl"
	{ b64_cnt = 2; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
	goto _again;
f41:
#line 263 "ejson.rl"
	{ b64_cnt = 1; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
	goto _again;
f15:
#line 267 "ejson.rl"
	{b64 = 0;}
#line 247 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'A'); }
	goto _again;
f16:
#line 267 "ejson.rl"
	{b64 = 0;}
#line 248 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'a' + 26 ); }
	goto _again;
f14:
#line 267 "ejson.rl"
	{b64 = 0;}
#line 249 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - '0' + 52 ); }
	goto _again;
f12:
#line 267 "ejson.rl"
	{b64 = 0;}
#line 250 "ejson.rl"
	{ b64 = (b64 << 6) | 62; }
	goto _again;
f13:
#line 267 "ejson.rl"
	{b64 = 0;}
#line 251 "ejson.rl"
	{ b64 = (b64 << 6) | 63; }
	goto _again;
f1:
#line 285 "ejson.rl"
	{ _value_start = p; }
#line 150 "ejson.rl"
	{
			if (d->open_data) {
				d->open_data(d);
				base64_hold = 0;
				if (!base64)
					base64 = (uint8_t*)alloca(128);
			}
		}
	goto _again;
f4:
#line 285 "ejson.rl"
	{ _value_start = p; }
#line 218 "ejson.rl"
	{ float_start = p; }
	goto _again;
f7:
#line 285 "ejson.rl"
	{ _value_start = p; }
#line 281 "ejson.rl"
	{ p--; {
			// prepush thing
			if (top == stack_size) {
				stack_size += 8;
				stack = realloc(stack, stack_size * sizeof(int));
			}
		{stack[top++] = cs; cs = 85; goto _again;}} }
	goto _again;
f6:
#line 285 "ejson.rl"
	{ _value_start = p; }
#line 282 "ejson.rl"
	{ p--; {
			// prepush thing
			if (top == stack_size) {
				stack_size += 8;
				stack = realloc(stack, stack_size * sizeof(int));
			}
		{stack[top++] = cs; cs = 37; goto _again;}} }
	goto _again;
f90:
#line 286 "ejson.rl"
	{ printf("### Value[%d] Error : '%s'\n", top, _value_start); }
#line 310 "ejson.rl"
	{ printf("### ejson Error : '%s'\n", p); }
	goto _again;
f81:
#line 135 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_string, &v); }
#line 130 "ejson.rl"
	{ d->close_object(d); }
#line 305 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f62:
#line 135 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_string, &v); }
#line 132 "ejson.rl"
	{ d->close_array(d); }
#line 292 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f88:
#line 139 "ejson.rl"
	{ v.u.v_bool = 1; d->set_value(d, ejson_driver_type_bool, &v); }
#line 130 "ejson.rl"
	{ d->close_object(d); }
#line 305 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f76:
#line 139 "ejson.rl"
	{ v.u.v_bool = 1; d->set_value(d, ejson_driver_type_bool, &v); }
#line 132 "ejson.rl"
	{ d->close_array(d); }
#line 292 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f86:
#line 140 "ejson.rl"
	{ v.u.v_bool = 0; d->set_value(d, ejson_driver_type_bool, &v); }
#line 130 "ejson.rl"
	{ d->close_object(d); }
#line 305 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f72:
#line 140 "ejson.rl"
	{ v.u.v_bool = 0; d->set_value(d, ejson_driver_type_bool, &v); }
#line 132 "ejson.rl"
	{ d->close_array(d); }
#line 292 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f87:
#line 141 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_null, NULL); }
#line 130 "ejson.rl"
	{ d->close_object(d); }
#line 305 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f74:
#line 141 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_null, NULL); }
#line 132 "ejson.rl"
	{ d->close_array(d); }
#line 292 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f82:
#line 168 "ejson.rl"
	{
			if (base64_hold && d->add_data)
				d->add_data(d, base64, base64_hold);
			if (d->close_data) d->close_data(d);
		}
#line 130 "ejson.rl"
	{ d->close_object(d); }
#line 305 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f64:
#line 168 "ejson.rl"
	{
			if (base64_hold && d->add_data)
				d->add_data(d, base64, base64_hold);
			if (d->close_data) d->close_data(d);
		}
#line 132 "ejson.rl"
	{ d->close_array(d); }
#line 292 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f2:
#line 285 "ejson.rl"
	{ _value_start = p; }
#line 196 "ejson.rl"
	{ v.u.v_int = 0; integer_sign = 1; }
#line 218 "ejson.rl"
	{ float_start = p; }
	goto _again;
f84:
#line 199 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 136 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_integer, &v); }
#line 130 "ejson.rl"
	{ d->close_object(d); }
#line 305 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f68:
#line 199 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 136 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_integer, &v); }
#line 132 "ejson.rl"
	{ d->close_array(d); }
#line 292 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f85:
#line 199 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 138 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_hex, &v); }
#line 130 "ejson.rl"
	{ d->close_object(d); }
#line 305 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f70:
#line 199 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 138 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_hex, &v); }
#line 132 "ejson.rl"
	{ d->close_array(d); }
#line 292 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f83:
#line 219 "ejson.rl"
	{ 
			int l = p - float_start;
			if (l >= sizeof(float_value)) {
				l = sizeof(float_value)-1;
			}
			memcpy(float_value, float_start, l);
			float_value[l] = 0;
			double lf = 0.0d; 
			sscanf(float_value, "%lg", &lf); 
			v.u.v_float = lf;
			float_start = NULL;
		}
#line 137 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_float, &v); }
#line 130 "ejson.rl"
	{ d->close_object(d); }
#line 305 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f66:
#line 219 "ejson.rl"
	{ 
			int l = p - float_start;
			if (l >= sizeof(float_value)) {
				l = sizeof(float_value)-1;
			}
			memcpy(float_value, float_start, l);
			float_value[l] = 0;
			double lf = 0.0d; 
			sscanf(float_value, "%lg", &lf); 
			v.u.v_float = lf;
			float_start = NULL;
		}
#line 137 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_float, &v); }
#line 132 "ejson.rl"
	{ d->close_array(d); }
#line 292 "ejson.rl"
	{ {cs = stack[--top];goto _again;} }
	goto _again;
f34:
#line 247 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'A'); }
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
	goto _again;
f35:
#line 248 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'a' + 26 ); }
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
	goto _again;
f33:
#line 249 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - '0' + 52 ); }
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
	goto _again;
f31:
#line 250 "ejson.rl"
	{ b64 = (b64 << 6) | 62; }
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
	goto _again;
f32:
#line 251 "ejson.rl"
	{ b64 = (b64 << 6) | 63; }
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
	goto _again;
f28:
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 247 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'A'); }
	goto _again;
f29:
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 248 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'a' + 26 ); }
	goto _again;
f27:
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 249 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - '0' + 52 ); }
	goto _again;
f25:
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 250 "ejson.rl"
	{ b64 = (b64 << 6) | 62; }
	goto _again;
f26:
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 251 "ejson.rl"
	{ b64 = (b64 << 6) | 63; }
	goto _again;
f51:
#line 261 "ejson.rl"
	{ b64_cnt = 2; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 247 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'A'); }
	goto _again;
f52:
#line 261 "ejson.rl"
	{ b64_cnt = 2; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 248 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'a' + 26 ); }
	goto _again;
f50:
#line 261 "ejson.rl"
	{ b64_cnt = 2; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 249 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - '0' + 52 ); }
	goto _again;
f48:
#line 261 "ejson.rl"
	{ b64_cnt = 2; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 250 "ejson.rl"
	{ b64 = (b64 << 6) | 62; }
	goto _again;
f49:
#line 261 "ejson.rl"
	{ b64_cnt = 2; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 251 "ejson.rl"
	{ b64 = (b64 << 6) | 63; }
	goto _again;
f45:
#line 263 "ejson.rl"
	{ b64_cnt = 1; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 247 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'A'); }
	goto _again;
f46:
#line 263 "ejson.rl"
	{ b64_cnt = 1; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 248 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'a' + 26 ); }
	goto _again;
f44:
#line 263 "ejson.rl"
	{ b64_cnt = 1; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 249 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - '0' + 52 ); }
	goto _again;
f42:
#line 263 "ejson.rl"
	{ b64_cnt = 1; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 250 "ejson.rl"
	{ b64 = (b64 << 6) | 62; }
	goto _again;
f43:
#line 263 "ejson.rl"
	{ b64_cnt = 1; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
#line 267 "ejson.rl"
	{b64 = 0;}
#line 251 "ejson.rl"
	{ b64 = (b64 << 6) | 63; }
	goto _again;
f39:
#line 267 "ejson.rl"
	{b64 = 0;}
#line 247 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'A'); }
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
	goto _again;
f40:
#line 267 "ejson.rl"
	{b64 = 0;}
#line 248 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - 'a' + 26 ); }
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
	goto _again;
f38:
#line 267 "ejson.rl"
	{b64 = 0;}
#line 249 "ejson.rl"
	{ b64 = (b64 << 6) | ((*p) - '0' + 52 ); }
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
	goto _again;
f36:
#line 267 "ejson.rl"
	{b64 = 0;}
#line 250 "ejson.rl"
	{ b64 = (b64 << 6) | 62; }
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
	goto _again;
f37:
#line 267 "ejson.rl"
	{b64 = 0;}
#line 251 "ejson.rl"
	{ b64 = (b64 << 6) | 63; }
#line 256 "ejson.rl"
	{ b64_cnt = 3; }
#line 158 "ejson.rl"
	{
			if (base64_hold + b64_cnt >= 128) {
				if (d->add_data)
					d->add_data(d, base64, base64_hold);
				base64_hold = 0;
			}
			if (base64)
				for (int s=16, i = 0; i < b64_cnt; i++, s-=8)
					base64[base64_hold++] = (b64 >> s) & 0xff;
		}
	goto _again;
f3:
#line 285 "ejson.rl"
	{ _value_start = p; }
#line 196 "ejson.rl"
	{ v.u.v_int = 0; integer_sign = 1; }
#line 197 "ejson.rl"
	{ integer_sign = -1; }
#line 218 "ejson.rl"
	{ float_start = p; }
	goto _again;
f5:
#line 285 "ejson.rl"
	{ _value_start = p; }
#line 196 "ejson.rl"
	{ v.u.v_int = 0; integer_sign = 1; }
#line 198 "ejson.rl"
	{ v.u.v_int = (v.u.v_int * 10) + ((*p) - '0'); }
#line 218 "ejson.rl"
	{ float_start = p; }
	goto _again;

_again:
	if ( cs == 0 )
		goto _out;
	if ( ++p != pe )
		goto _resume;
	_test_eof: {}
	if ( p == eof )
	{
	switch ( _ejson_eof_actions[cs] ) {
	case 62:
#line 135 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_string, &v); }
	break;
	case 76:
#line 139 "ejson.rl"
	{ v.u.v_bool = 1; d->set_value(d, ejson_driver_type_bool, &v); }
	break;
	case 72:
#line 140 "ejson.rl"
	{ v.u.v_bool = 0; d->set_value(d, ejson_driver_type_bool, &v); }
	break;
	case 74:
#line 141 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_null, NULL); }
	break;
	case 64:
#line 168 "ejson.rl"
	{
			if (base64_hold && d->add_data)
				d->add_data(d, base64, base64_hold);
			if (d->close_data) d->close_data(d);
		}
	break;
	case 24:
#line 268 "ejson.rl"
	{ printf("### base64 Error : '%s'\n", p); }
	break;
	case 61:
#line 286 "ejson.rl"
	{ printf("### Value[%d] Error : '%s'\n", top, _value_start); }
	break;
	case 68:
#line 199 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 136 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_integer, &v); }
	break;
	case 70:
#line 199 "ejson.rl"
	{  v.u.v_int *= integer_sign; }
#line 138 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_hex, &v); }
	break;
	case 66:
#line 219 "ejson.rl"
	{ 
			int l = p - float_start;
			if (l >= sizeof(float_value)) {
				l = sizeof(float_value)-1;
			}
			memcpy(float_value, float_start, l);
			float_value[l] = 0;
			double lf = 0.0d; 
			sscanf(float_value, "%lg", &lf); 
			v.u.v_float = lf;
			float_start = NULL;
		}
#line 137 "ejson.rl"
	{ d->set_value(d, ejson_driver_type_float, &v); }
	break;
#line 3724 "ejson.c"
	}
	}

	_out: {}
	}

#line 315 "ejson.rl"

	if (stack) free(stack);
	return 0;
};

